export const InputType = {
  EMAIL: 'email',
  PASSWORD: 'password',
  TEXT: 'text',
  URL: 'url',
} as const;

export const FORM_FIELDS = {
  EMAIL: {
    label: 'Email',
    name: 'email',
    placeholder: 'Email',
    errorMessage: 'Email is required',
    type: InputType.EMAIL,
  },
  PASSWORD: {
    label: 'Password',
    name: 'password',
    placeholder: 'Password',
    errorMessage: 'Password is required',
    type: InputType.PASSWORD,
  },
  TITLE: {
    label: 'Title',
    name: 'title',
    placeholder: 'Title',
    errorMessage: 'Title is required',
    type: InputType.TEXT,
  },
  LICENSE: {
    label: 'License',
    name: 'license',
    placeholder: 'URL',
    errorMessage: 'URL is required',
    type: InputType.URL,
  },
  IMPRINT: {
    label: 'Imprint',
    name: 'imprint',
    placeholder: 'Imprint',
    errorMessage: 'Imprint is required',
  },
  WORK_TYPE: {
    label: 'Work Type',
    name: 'workType',
    placeholder: 'Work Type',
    errorMessage: 'Work Type is required',
  },
  COPYRIGHT_HOLDER: {
    label: 'Copyright holder',
    name: 'copyrightHolder',
    placeholder: 'Copyright holder',
    type: InputType.TEXT,
  },
  // FIRST_NAME: 'firstName',
  // LAST_NAME: 'lastName',
  // FULL_NAME: 'fullName',
  // SHORT_NAME: 'shortName',
  // NAME: 'name',
  // WEBSITE_URL: 'websiteUrl',
  // URL: 'url',
  // DESCRIPTION: 'description',
  // WORK_STATUS: 'workStatus',
  // SERIES_TYPE: 'seriesType',
  // PUBLICATION_TYPE: 'publicationType',
  // DOI: 'doi',
  // ORCID: 'orcid',
  // ROLE: 'role',
  // CREATED_AT: 'createdAt',
  // UPDATED_AT: 'updatedAt',
  // ISSN_PRINT: 'isnnPrint',
  // ISSN_DIGITAL: 'isnnDigital',
  // PAGE_BREAKDOWN: 'pageBreakdown',
  // COUNTRY_CODE: 'countryCode',
} as const;
