import { ERRORS } from '@/constants';

const {
  EMAIL_REQUIRED,
  PASSWORD_REQUIRED,
  TITLE_REQUIRED,
  URL_REQUIRED,
  IMPRINT_REQUIRED,
  WORK_TYPE_REQUIRED,
  COPYRIGHT_HOLDER_REQUIRED,
} = ERRORS;

export const InputType = {
  EMAIL: 'email',
  PASSWORD: 'password',
  TEXT: 'text',
  URL: 'url',
} as const;

export const FORM_FIELDS = {
  EMAIL: {
    label: 'Email',
    name: 'email',
    placeholder: 'Email',
    errorMessage: EMAIL_REQUIRED,
    type: InputType.EMAIL,
  },
  PASSWORD: {
    label: 'Password',
    name: 'password',
    placeholder: 'Password',
    errorMessage: PASSWORD_REQUIRED,
    type: InputType.PASSWORD,
  },
  TITLE: {
    label: 'Title',
    name: 'title',
    placeholder: 'Title',
    errorMessage: TITLE_REQUIRED,
    type: InputType.TEXT,
    defaultValue: '',
  },
  LICENSE: {
    label: 'License',
    name: 'license',
    placeholder: 'URL',
    errorMessage: URL_REQUIRED,
    type: InputType.URL,
    defaultValue: '',
  },
  IMPRINT_ID: {
    label: 'Imprint',
    name: 'imprintId',
    placeholder: 'Imprint',
    errorMessage: IMPRINT_REQUIRED,
    defaultValue: '',
  },
  WORK_TYPE: {
    label: 'Work Type',
    name: 'workType',
    placeholder: 'Work Type',
    errorMessage: WORK_TYPE_REQUIRED,
    defaultValue: '',
  },
  COPYRIGHT_HOLDER: {
    label: 'Copyright holder',
    name: 'copyrightHolder',
    placeholder: 'Copyright holder',
    errorMessage: COPYRIGHT_HOLDER_REQUIRED,
    type: InputType.TEXT,
  },
  // FIRST_NAME: 'firstName',
  // LAST_NAME: 'lastName',
  // FULL_NAME: 'fullName',
  // SHORT_NAME: 'shortName',
  // NAME: 'name',
  // WEBSITE_URL: 'websiteUrl',
  // URL: 'url',
  // DESCRIPTION: 'description',
  // WORK_STATUS: 'workStatus',
  // SERIES_TYPE: 'seriesType',
  // PUBLICATION_TYPE: 'publicationType',
  // DOI: 'doi',
  // ORCID: 'orcid',
  // ROLE: 'role',
  // CREATED_AT: 'createdAt',
  // UPDATED_AT: 'updatedAt',
  // ISSN_PRINT: 'isnnPrint',
  // ISSN_DIGITAL: 'isnnDigital',
  // PAGE_BREAKDOWN: 'pageBreakdown',
  // COUNTRY_CODE: 'countryCode',
} as const;
