export const FORM_FIELDS = {
  EMAIL: 'email',
  PASSWORD: 'password',
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
  FULL_NAME: 'fullName',
  SHORT_NAME: 'shortName',
  NAME: 'name',
  WEBSITE_URL: 'websiteUrl',
  URL: 'url',
  DESCRIPTION: 'description',
  WORK_TYPE: 'workType',
  WORK_STATUS: 'workStatus',
  SERIES_TYPE: 'seriesType',
  PUBLICATION_TYPE: 'publicationType',
  DOI: 'doi',
  ORCID: 'orcid',
  ROLE: 'role',
  CREATED_AT: 'createdAt',
  UPDATED_AT: 'updatedAt',
  ISSN_PRINT: 'isnnPrint',
  ISSN_DIGITAL: 'isnnDigital',
  PAGE_BREAKDOWN: 'pageBreakdown',
  COUNTRY_CODE: 'countryCode',
} as const;
