export const ROUTES = {
  ROOT: '/',
  LOGIN: '/auth/login',
  DASHBOARD: '/admin/dashboard',
  NEW_WORK: '/admin/works/new',
  CREATE_WORK: '/admin/works/new/create',
  WORK_PAGE: (id: string) => `/admin/works/${id}`,
  WORKS: '/admin/works',
  BOOKS: '/admin/books',
  CHAPTERS: '/admin/chapters',
  PUBLICATIONS: '/admin/publications',
  PUBLISHERS: '/admin/publishers',
  IMPRINTS: '/admin/imprints',
  CONTRIBUTORS: '/admin/contributors',
  SERIES: '/admin/series',
  INSTITUTIONS: '/admin/institutions',
} as const;
