/**
 * BIC (Book Industry Communication) Standard Subject Categories
 * Maps BIC codes to their full descriptive names
 * Note: BIC codes were officially made obsolete in February 2024 and replaced by Thema
 * Auto-generated from bic.csv
 */
export const BIC_CODES: Record<string, string> = {
  'A': 'The Arts',
  'AB': 'The arts: general issues',
  'ABA': 'Theory of art',
  'ABC': 'Conservation, restoration & care of artworks',
  'ABK': 'Individual artists, art monographs',
  'ABQ': 'Art techniques & principles',
  'ACB': 'Individual photographers',
  'AFF': 'Film history, theory & criticism',
  'AF': 'Cinema, TV & Radio',
  'AFX': 'History of cinema & TV',
  'AG': 'Music',
  'AGA': 'Music: styles & genres',
  'AGC': 'Theory of music & musicology',
  'AGR': 'Individual composers & musicians, specific bands & groups',
  'AGZ': 'Music: techniques & principles',
  'AJ': 'Photography & photographs',
  'AJC': 'Photographic equipment & techniques: general',
  'AJT': 'Photography: collections',
  'AK': 'Industrial / commercial art & design',
  'AKB': 'Individual designers',
  'AKC': 'Graphic design',
  'AKD': 'Typography & lettering',
  'AKH': 'Book design',
  'AKL': 'Illustration & commercial art',
  'AKP': 'Product design',
  'AKT': 'Fashion & textiles: design',
  'AMB': 'Architecture: aesthetics',
  'AMC': 'Architectural structure & design',
  'AMD': 'Architecture: professional practice',
  'AMG': 'Architecture: public, commercial & industrial buildings',
  'AMK': 'Architecture: interior design',
  'AML': 'Landscape art & architecture',
  'AMN': 'Individual architects & architectural firms',
  'AMR': 'Architecture: residential & domestic buildings',
  'AMV': 'Sustainable architecture',
  'AMX': 'History of architecture',
  'AT': 'Performing arts',
  'ATC': 'Theatre studies',
  'ATD': 'Theatre: individual actors & performers',
  'ATF': 'Theatre direction & production',
  'ATJ': 'Dance & other performing arts',
  'B': 'Biography & True Stories',
  'BG': 'Biography: general',
  'BGA': 'Autobiography: general',
  'BGB': 'Biography: business & industry',
  'BGF': 'Biography: historical, political & military',
  'BGL': 'Biography: literary',
  'BGM': 'Biography: royalty',
  'BGR': 'Biography: religious & spiritual',
  'BGS': 'Biography: sport',
  'BGX': 'Biography: arts & entertainment',
  'BJ': 'Diaries, letters & journals',
  'BK': 'Collected biographies',
  'BM': 'Memoirs',
  'BT': 'True stories',
  'BTC': 'True stories: discovery / historical / scientific',
  'BTH': 'True stories: heroism, endurance & survival',
  'BTM': 'True war & combat stories',
  'C': 'Language',
  'CB': 'Language: reference & general',
  'CBA': 'Language: history & general works',
  'CBD': 'Dictionaries',
  'CBG': 'Grammar, syntax & morphology',
  'CBP': 'Phonetics, phonology',
  'CBV': 'Creative writing & creative writing guides',
  'CBW': 'Writing & editing guides',
  'CBX': 'Language teaching & learning (other than ELT)',
  'CF': 'Literary studies: general',
  'CFA': 'Literary studies: classical, early & medieval',
  'CFD': 'Literary studies: c 1800 to c 1900',
  'CFF': 'Literary studies: c 1900 to c 2000',
  'CFK': 'Literary studies: from c 2000',
  'CFP': 'Literary studies: poetry & poets',
  'CFQ': 'Literary studies: plays & playwrights',
  'CFX': 'Literary studies: fiction, novelists & prose writers',
  'CJ': 'Language teaching & learning material & coursework',
  'CJA': 'ELT: learning material & coursework',
  'CJB': 'ELT: background & reference material',
  'D': 'Literature & Literary Studies',
  'DC': 'Poetry',
  'DCA': 'Poetry by individual poets',
  'DCF': 'Poetry anthologies (various poets)',
  'DCQ': 'Poetry: from c 1900 to c 2000',
  'DD': 'Plays, playscripts',
  'DDA': 'Plays, playscripts: from c 1800 to c 1900',
  'DDS': 'Shakespeare plays',
  'DN': 'Anthologies (non-poetry)',
  'DQ': 'Anthologies (non-poetry), various authors',
  'DS': 'Literature: history & criticism',
  'DSA': 'Literary studies: general',
  'DSB': 'Literary studies: ancient, classical & medieval',
  'DSC': 'Literary studies: c 1500 to c 1800',
  'DSG': 'Literary studies: general',
  'DSK': 'Literary studies: fiction, novelists & prose writers',
  'DSR': 'Literary studies: poetry & poets',
  'F': 'Fiction & Related Items',
  'FA': 'Modern & contemporary fiction (post c 1945)',
  'FB': 'Thriller / suspense',
  'FBC': 'Crime & mystery',
  'FC': 'Historical fiction',
  'FD': 'Adventure',
  'FF': 'Horror & ghost stories',
  'FH': 'Humour',
  'FJ': 'Fantasy',
  'FK': 'Science fiction',
  'FL': 'Horror & supernatural fiction',
  'FM': 'Romance',
  'FP': 'Erotica',
  'FT': 'Sagas',
  'FV': 'War & combat fiction',
  'FW': 'Religious & spiritual fiction',
  'FX': 'Fiction: special features',
  'FXL': 'Fiction in translation',
  'FY': 'Fiction: related items',
  'FYB': 'Literary companions',
  'FZ': 'Fiction companions',
  'G': 'Reference, Information & Interdisciplinary Subjects',
  'GB': 'Encyclopaedias & reference works',
  'GBC': 'Encyclopaedias',
  'GT': 'Interdisciplinary studies',
  'GTC': 'Communication studies',
  'GTD': 'Development studies',
  'GTM': 'Regional studies',
  'GTU': 'Peace studies & conflict resolution',
  'GTV': 'Environmental studies',
  'H': 'Humanities',
  'HB': 'History',
  'HBA': 'History: theory & methods',
  'HBG': 'General & world history',
  'HBJ': 'Regional & national history',
  'HBJD': 'European history',
  'HBJF': 'Asian history',
  'HBJH': 'African history',
  'HBJK': 'History of the Americas',
  'HBL': 'History: earliest times to present day',
  'HBLA': 'Ancient history: to c 500 CE',
  'HBLC': 'Early history: c 500 to c 1450/1500',
  'HBLL': 'Modern history to 20th century: c 1700 to c 1900',
  'HBLW': '20th century history: c 1900 to c 2000',
  'HBLX': '21st century history: from c 2000 -',
  'HBT': 'History: specific events & topics',
  'HBTB': 'Social & cultural history',
  'HBTD': 'Oral history',
  'HBTG': 'Historical geography',
  'HBTH': 'Economic history',
  'HBTJ': 'Industrial history',
  'HBTK': 'Military history',
  'HBTP': 'Historical maps & atlases',
  'HBTR': 'National liberation & independence',
  'HBTS': 'Slavery & abolition of slavery',
  'HBTV': 'Revolutions, uprisings, rebellions',
  'HBTW': 'Revolutionary groups & movements',
  'HBTZ': 'Genocides & ethnic cleansing',
  'HBW': 'Military history',
  'HBWF': 'Battles & campaigns',
  'HBWG': 'Equipment, weapons & technology',
  'HBWN': 'Naval warfare & warships',
  'HBWQ': 'Air warfare & air forces',
  'J': 'Society & Social Sciences',
  'JF': 'Politics & government',
  'JFC': 'Political structures: democracy',
  'JFF': 'Political structures: totalitarianism & dictatorship',
  'JFH': 'Political ideologies',
  'JFM': 'Political activism',
  'JFS': 'Political control & freedoms',
  'JH': 'Sociology & anthropology',
  'JHB': 'Sociology',
  'JHBA': 'Social theory',
  'JHBD': 'Population & demography',
  'JHM': 'Anthropology',
  'JHMC': 'Social & cultural anthropology',
  'JN': 'Education',
  'JNA': 'Philosophy & theory of education',
  'JNB': 'History of education',
  'JNC': 'Educational systems & structures',
  'JND': 'Schools',
  'JNF': 'Educational strategies & policy',
  'JNH': 'Higher & further education, tertiary education',
  'JNL': 'Adult education, continuous learning',
  'JNM': 'Training for specific professions & occupations',
  'JNP': 'Educational equipment & technology, computer-aided learning (CAL)',
  'JNT': 'Teaching skills & techniques',
  'JNV': 'Educational material',
  'JP': 'Warfare & defence',
  'JPA': 'Theory of warfare & military science',
  'JPB': 'Defence strategy, planning & research',
  'JPC': 'Weapons systems & military equipment',
  'JPH': 'Weapons & equipment',
  'JPP': 'Peace-keeping operations',
  'JPS': 'Terrorism, armed struggle',
  'JPW': 'War & defence operations',
  'K': 'Economics, Finance, Business & Management',
  'KC': 'Economics',
  'KCA': 'Economic theory & philosophy',
  'KCB': 'Macroeconomics',
  'KCC': 'Microeconomics',
  'KCF': 'International economics',
  'KCG': 'Economic growth',
  'KCL': 'Labour / income economics',
  'KCS': 'Economic statistics',
  'KCX': 'Economic history',
  'KF': 'Finance & accounting',
  'KFA': 'Finance: general',
  'KFC': 'Public finance & taxation',
  'KFF': 'Corporate finance',
  'KFH': 'Personal finance',
  'KFK': 'Banking',
  'KFL': 'Accounting',
  'KJB': 'Business & management: general',
  'KJC': 'Business strategy',
  'KJD': 'Decision-making techniques',
  'KJE': 'E-commerce: business aspects',
  'KJG': 'Business competition',
  'KJH': 'Entrepreneurship',
  'KJL': 'Accounting & bookkeeping',
  'KJM': 'Management & management techniques',
  'KJMV': 'Management of specific areas',
  'KJP': 'Project management',
  'KJS': 'Sales & marketing',
  'KJSA': 'Sales & marketing management',
  'KJSB': 'Advertising',
  'KJSM': 'Market research',
  'KJT': 'Business & the environment, \'green\' approaches to business',
  'KJU': 'Organizational theory & behaviour',
  'KJV': 'Office & workplace',
  'KJW': 'Business ethics & social responsibility',
  'L': 'Law',
  'LA': 'Jurisprudence & general issues',
  'LAB': 'Methods, theory & philosophy of law',
  'LAF': 'Legal profession: general',
  'LAG': 'Legal skills (general)',
  'LAH': 'Comparative law',
  'LAM': 'Public international law',
  'LAN': 'Laws of Specific jurisdictions',
  'LAQ': 'IT & Communications law: general',
  'LAT': 'Taxation & revenue law',
  'LAZ': 'Legal profession: court practice & procedure',
  'LB': 'International law',
  'LBB': 'Public international law: general',
  'LBD': 'Public international law: treaties & other sources',
  'LBG': 'International economic & trade law',
  'LBH': 'Public international law: human rights',
  'LBJ': 'Public international law: environment',
  'LN': 'Laws of Specific jurisdictions',
  'M': 'Medicine',
  'MB': 'Medicine: general issues',
  'MBN': 'Medical profession',
  'MBP': 'Medical ethics & professional conduct',
  'MBS': 'Medical sociology',
  'MBX': 'History of medicine',
  'MF': 'Pre-clinical medicine: basic sciences',
  'MFG': 'Anatomy',
  'MFK': 'Human reproduction, growth & development',
  'MFN': 'Pharmacology',
  'MH': 'Nursing & ancillary services',
  'MHC': 'Nursing: specialisms',
  'MJ': 'Clinical & internal medicine',
  'MJA': 'Medical diagnosis',
  'MJC': 'Diseases & disorders',
  'MJCG': 'Cardiovascular medicine',
  'MJCJ': 'Gastrointestinal medicine & gastroenterology',
  'MJCL': 'Oncology',
  'MK': 'Medical specialties, branches of medicine',
  'MKC': 'Anaesthetics',
  'MKD': 'Dermatology',
  'MKE': 'Emergency medicine',
  'MKF': 'Paediatrics',
  'MKG': 'Geriatric medicine',
  'MKH': 'Pathology',
  'MKJ': 'Gynaecology & obstetrics',
  'MKM': 'Radiology',
  'MKN': 'Psychiatry',
  'MKP': 'Surgery',
  'MKR': 'Therapy & therapeutics',
  'MM': 'Other branches of medicine',
  'MMB': 'Dentistry',
  'MMH': 'Optometry & optics',
  'MMP': 'Pharmacy / dispensing',
  'MMZ': 'Veterinary medicine',
  'MQ': 'Nursing & ancillary services',
  'MQC': 'Nursing',
  'MQCA': 'Nursing: general & principles',
  'MQCB': 'Nursing: specialisms',
  'MQF': 'Complementary medicine',
  'MQFB': 'Acupuncture',
  'MQH': 'First aid & paramedical services',
  'MQP': 'Occupational therapy',
  'MQR': 'Physiotherapy',
  'MQS': 'Dietetics & nutrition',
  'MQV': 'Midwifery',
  'MX': 'Public health & preventive medicine',
  'MXD': 'Occupational & industrial medicine',
  'N': 'History & Archaeology',
  'NH': 'History',
  'P': 'Mathematics & Science',
  'PB': 'Mathematics',
  'PBB': 'Philosophy of mathematics',
  'PBC': 'Mathematical foundations',
  'PBD': 'Discrete mathematics',
  'PBF': 'Algebra',
  'PBG': 'Groups & group theory',
  'PBH': 'Number theory',
  'PBK': 'Calculus & mathematical analysis',
  'PBM': 'Geometry',
  'PBP': 'Topology',
  'PBS': 'Probability & statistics',
  'PBT': 'Stochastics',
  'PBU': 'Optimization',
  'PBV': 'Combinatorics & graph theory',
  'PBW': 'Applied mathematics',
  'PBWH': 'Mathematical modelling',
  'PBWL': 'Numerical analysis',
  'PD': 'Science: general issues',
  'PDA': 'Philosophy of science',
  'PDC': 'Scientific equipment, experiments & techniques',
  'PDG': 'Industrial applications of scientific research & technological innovation',
  'PDR': 'Impact of science & technology on society',
  'PDX': 'History of science',
  'PDZ': 'Popular science',
  'PG': 'Astronomy, space & time',
  'PGC': 'Cosmology & the universe',
  'PGG': 'Galaxies & stars',
  'PGK': 'Solar system: the Sun & planets',
  'PGM': 'Space exploration',
  'PGS': 'Time (chronology), time systems & standards',
  'PH': 'Physics',
  'PHD': 'Classical mechanics',
  'PHF': 'Materials / States of matter',
  'PHH': 'Thermodynamics & heat',
  'PHJ': 'Optics (light)',
  'PHK': 'Electricity, electromagnetism & magnetism',
  'PHL': 'Sound & acoustics',
  'PHN': 'Nuclear physics',
  'PHQ': 'Quantum physics (quantum mechanics & quantum field theory)',
  'PHR': 'Relativity physics',
  'PHS': 'Wave mechanics (vibration & waves)',
  'PHU': 'Atomic & molecular physics',
  'PHV': 'Applied physics',
  'PN': 'Chemistry',
  'PNB': 'Analytical chemistry',
  'PNC': 'Inorganic chemistry',
  'PND': 'Organic chemistry',
  'PNF': 'Physical chemistry',
  'PNK': 'Biochemistry',
  'PNR': 'Polymer chemistry',
  'PNT': 'Industrial chemistry & manufacturing technologies',
  'PS': 'Biology, life sciences',
  'PSA': 'Life sciences: general issues',
  'PSB': 'Biochemistry',
  'PSC': 'Molecular biology',
  'PSD': 'Genetics (non-medical)',
  'PSE': 'Evolutionary biology',
  'PSF': 'Ecology, biosphere',
  'PSG': 'Microbiology (non-medical)',
  'PSP': 'Hydrobiology',
  'PSQ': 'Plant biology',
  'PST': 'Zoology & animal sciences',
  'PSTF': 'Palaeontology',
  'Q': 'Philosophy & Religion',
  'QD': 'Philosophy',
  'QDH': 'History of Western philosophy',
  'QDT': 'Topics in philosophy',
  'QDTK': 'Philosophy of language',
  'QDTM': 'Philosophy of mind',
  'QDTN': 'Philosophy of science',
  'QDX': 'Popular philosophy',
  'QR': 'Religion & beliefs',
  'QRA': 'Religion: general',
  'QRAB': 'Philosophy of religion',
  'QRAC': 'Comparative religion',
  'QRAF': 'Interfaith relations',
  'QRAM': 'Religious issues & debates',
  'QRAX': 'History of religion',
  'QRD': 'Hinduism',
  'QRF': 'Buddhism',
  'QRJ': 'Judaism',
  'QRM': 'Christianity',
  'QRMA': 'The Bible',
  'QRMB': 'Biblical studies & exegesis',
  'QRMC': 'Christian theology',
  'QRMD': 'Christian worship',
  'QRMF': 'Christian Churches & denominations',
  'QRMH': 'Christian institutions & organizations',
  'QRML': 'Church history',
  'QRP': 'Islam',
  'QRPA': 'The Koran (Qur\'an)',
  'QRPB': 'Hadith',
  'QRPF': 'Islamic life & practice',
  'QRR': 'Other religions & spiritual beliefs',
  'QRRL': 'Ancient religions & mythologies',
  'QRRN': 'Nature & existence of God',
  'QRRP': 'Monotheism',
  'QRRS': 'Polytheism',
  'QRRV': 'Syncretism & interreligious matters',
  'QRRY': 'Alternative belief systems',
  'QRYX': 'Alternative belief systems',
  'R': 'Earth Sciences, Geography, Environment, Planning',
  'RB': 'Earth sciences',
  'RBC': 'Geology, geomorphology & the lithosphere',
  'RBGB': 'Sedimentology & pedology',
  'RBGL': 'Mineralogy & gems',
  'RBGM': 'Petrology, petrography & mineralogy',
  'RBK': 'Hydrology & the hydrosphere',
  'RBP': 'Meteorology & climatology',
  'RBX': 'Palaeontology',
  'RG': 'Geography',
  'RGB': 'Physical geography & topography',
  'RGC': 'Human geography',
  'RGL': 'Geographical information systems (GIS) & remote sensing',
  'RGM': 'Cartography, map-making & projections',
  'RN': 'Environment',
  'RNA': 'Environmentalist thought & ideology',
  'RNC': 'Applied ecology',
  'RND': 'Environmental management',
  'RNF': 'Conservation of the environment',
  'RNH': 'Climate change',
  'RNK': 'Pollution & threats to the environment',
  'RNP': 'Sustainability',
  'RNR': 'Waste management',
  'RP': 'Regional & area planning',
  'RPC': 'Urban & municipal planning',
  'RPG': 'Regional planning',
  'RPT': 'Transport planning',
  'S': 'Sports & Outdoor Recreation',
  'SC': 'Sports & outdoor recreation: general',
  'SCA': 'Sports training & coaching',
  'SCB': 'Sports psychology',
  'SCD': 'Sports equipment & supplies',
  'SCF': 'Sports facilities & management',
  'SCG': 'Sports for specific age groups',
  'SCK': 'Sports science, physical education',
  'SCZ': 'History of sport',
  'SD': 'Ball games',
  'SDP': 'Association football (soccer)',
  'SDQ': 'Rugby football',
  'SDR': 'Cricket',
  'SDS': 'Baseball',
  'SDT': 'Basketball',
  'SDU': 'Hockey',
  'SDZ': 'Other ball games',
  'SE': 'Racket games',
  'SEJ': 'Tennis',
  'SEK': 'Badminton',
  'SFB': 'Golf',
  'SFH': 'Track & field sports, athletics',
  'SFV': 'Athletics & gymnastics',
  'SH': 'Combat sports & self-defence',
  'SHB': 'Boxing',
  'SHD': 'Wrestling',
  'SHF': 'Martial arts',
  'SJ': 'Water sports & recreations',
  'SJB': 'Swimming & diving',
  'SJH': 'Canoeing',
  'SJP': 'Sailing & boating',
  'SJQ': 'Surfing, windsurfing, waterskiing',
  'SK': 'Winter sports',
  'SKA': 'Ice skating',
  'SKC': 'Ice hockey',
  'SKD': 'Skiing & snowboarding',
  'SL': 'Equestrian & animal sports',
  'SLB': 'Horse racing',
  'SLC': 'Showjumping & horsemanship',
  'SM': 'Cycling & wheeled sports',
  'SMC': 'Cycling',
  'SMK': 'Motor sports',
  'SN': 'Air sports & recreations',
  'SP': 'Outdoor pursuits',
  'SPC': 'Hiking & camping',
  'SPD': 'Mountaineering & climbing',
  'SPF': 'Caving & potholing',
  'SPG': 'Orienteering',
  'SPJ': 'Field sports: fishing, hunting, shooting',
  'SPJF': 'Fishing, angling',
  'SPJH': 'Hunting',
  'SZD': 'Extreme sports',
  'T': 'Technology, Engineering, Agriculture',
  'TB': 'Technology: general issues',
  'TBC': 'History of engineering & technology',
  'TBD': 'Technology: general issues',
  'TBG': 'Inventions & inventors',
  'TBJ': 'Engineering: general',
  'TBM': 'Materials science',
  'TBN': 'Nanotechnology',
  'TBX': 'History of engineering & technology',
  'TC': 'Building & construction',
  'TCD': 'Technical design',
  'TD': 'Industrial chemistry & manufacturing technologies',
  'TDC': 'Industrial chemistry',
  'TDCC': 'Ceramics, glass & clay technology',
  'TDCP': 'Paints & coatings technology',
  'TDCQ': 'Plastics & polymers',
  'TDCR': 'Rubber technology',
  'TF': 'Other manufacturing technologies',
  'TFC': 'Textiles technology',
  'TFM': 'Printing & reprographics technology',
  'TFX': 'Food processing & technology',
  'TG': 'Mechanical engineering & materials',
  'TGB': 'Mechanical engineering: general',
  'TGM': 'Engineering: mechanics of solids',
  'TGP': 'Tribology (friction & lubrication)',
  'TH': 'Energy technology & engineering',
  'THF': 'Fossil fuel technologies',
  'THFG': 'Coal technology',
  'THK': 'Nuclear power & engineering',
  'THR': 'Electrical engineering',
  'THRB': 'Electrical power generation & distribution',
  'THV': 'Alternative & renewable energy sources & technology',
  'THVB': 'Biofuels',
  'THVS': 'Solar power & energy',
  'THVW': 'Wind power & energy',
  'TJ': 'Electronics & communications engineering',
  'TJF': 'Electronics engineering',
  'TJK': 'Communications engineering / telecommunications',
  'TJKD': 'WAP (wireless) technology',
  'TJKR': 'Radio technology',
  'TJKS': 'Satellite communication technology',
  'TJKT': 'Telephone technology',
  'TJM': 'Automatic control engineering',
  'TJMG': 'Mechatronics',
  'TN': 'Civil engineering, surveying & building',
  'TNC': 'Civil engineering & construction',
  'TNCB': 'Building construction & materials',
  'TNCC': 'Building trades',
  'TNCD': 'Structural engineering',
  'TNCL': 'Municipal & local government engineering',
  'TNCR': 'Road & highway engineering',
  'TNCS': 'Railway engineering',
  'TNCT': 'Hydraulic engineering',
  'TND': 'Surveying',
  'TQ': 'Environmental science, engineering & technology',
  'TQD': 'Environmental science, engineering & technology: general',
  'TQK': 'Water supply & treatment',
  'TQS': 'Sanitary & municipal engineering',
  'TR': 'Transport technology & trades',
  'TRC': 'Automotive technology & trades',
  'TRCS': 'Vehicle maintenance & manuals',
  'TRP': 'Aerospace & aviation technology',
  'TRW': 'Railway technology',
  'TRX': 'Shipbuilding & marine technology',
  'TT': 'Other technologies & applied sciences',
  'TTA': 'Minerals, mining & extractive industries',
  'TTB': 'Military technology',
  'TTC': 'Space science',
  'TTD': 'Space exploration',
  'TTM': 'Military technology',
  'TTMP': 'Weapons & military equipment',
  'TTN': 'Agricultural science',
  'TTNC': 'Organic farming',
  'TVB': 'Television: content & production',
  'TVG': 'Television broadcasting',
  'U': 'Computing & Information Technology',
  'UB': 'Information technology: general',
  'UF': 'Computer science',
  'UFC': 'Algorithms & data structures',
  'UFK': 'Artificial intelligence',
  'UFM': 'Computer programming / software development',
  'UFS': 'Image processing',
  'UFX': 'Pattern recognition',
  'UL': 'Operating systems & graphical user interfaces (GUI)',
  'UMA': 'Computer architecture & logic design',
  'UMB': 'Computer communications & networking',
  'UMP': 'Computer programming / software development',
  'UMTC': 'Computer graphics',
  'UN': 'Databases',
  'UNF': 'Database programming',
  'UQ': 'Computer security',
  'UR': 'Internet: general',
  'URB': 'E-commerce: business aspects',
  'URF': 'Internet guides & online services',
  'URH': 'Web programming',
  'URJ': 'Web graphics & design',
  'URY': 'Internet: security & privacy',
  'UT': 'Digital lifestyle',
  'UTB': 'Digital or electronic entertainment',
  'UTC': 'Consumer advice: electronics',
  'UTN': 'Consumer advice: office & business equipment',
  'UTV': 'Consumer advice: gadgets',
  'UTW': 'Digital photography: consumer',
  'UTY': 'Computer games',
  'V': 'Health & Personal Development',
  'VF': 'Family & health',
  'VFB': 'Advice on parenting',
  'VFBS': 'Advice on parenting: babies & toddlers',
  'VFDC': 'Pregnancy, birth & baby care: advice & issues',
  'VFJ': 'Children\'s health',
  'VFM': 'Coping with personal problems',
  'VFMC': 'Coping with drug & alcohol abuse',
  'VFMD': 'Coping with death & bereavement',
  'VFMG': 'Coping with disability',
  'VFMS': 'Coping with eating disorders',
  'VFV': 'Family & relationships',
  'VFVC': 'Dating, relationships, living together & marriage',
  'VFVD': 'Divorce, separation & relationship breakdown',
  'VFVK': 'Single people',
  'VFVS': 'Sex & sexuality',
  'VFX': 'Men\'s health',
  'VFZ': 'Fitness & diet',
  'VFZD': 'Fitness & exercise',
  'VFZF': 'Diets & dieting',
  'VG': 'Home & house maintenance',
  'VGC': 'Gardening',
  'VGH': 'Gardens (descriptions, history, etc.)',
  'VGM': 'Garden features',
  'VGR': 'Gardening: plants',
  'VGV': 'Gardening: techniques',
  'VJ': 'Cookery / food & drink etc.',
  'VJB': 'National & regional cuisine',
  'VJBC': 'European cookery',
  'VJBF': 'Asian cookery',
  'VJBM': 'Cookery: American',
  'VJD': 'Cookery by ingredient',
  'VJDC': 'Vegetarian cookery',
  'VJDH': 'Cookery for the sick & convalescent',
  'VJF': 'Cookery for special occasions',
  'VJK': 'Cookery: meals & courses',
  'VJL': 'Cookery with specific gadgets',
  'VJM': 'Cookery dishes & courses: general',
  'VJMP': 'Cookery dishes & courses: cakes, baking, icing & sugarcraft',
  'VJMQ': 'Cookery dishes & courses: desserts',
  'VJMS': 'Cookery dishes & courses: soups & starters',
  'VJT': 'Drinks: general',
  'VM': 'Mind, body, spirit',
  'VMB': 'Psychic powers & psychic phenomena',
  'VMF': 'Fortune-telling & divination',
  'VMFA': 'Astrology',
  'VMFH': 'Horoscopes & zodiac',
  'VMH': 'Complementary therapies, healing & health',
  'VMHC': 'Acupuncture & acupressure',
  'VMHF': 'Aromatherapy & essential oils',
  'VMHH': 'Herbal medicine',
  'VMHM': 'Massage',
  'VMHQ': 'Reflexology',
  'VMHR': 'Reiki',
  'VMHS': 'Yoga',
  'VMJ': 'Dreams & dream interpretation',
  'VMK': 'Body, mind & spirit: meditation & visualization',
  'VMP': 'Mysticism, magic & ritual',
  'VMPC': 'Witchcraft & Wicca',
  'VMPG': 'Shamanism, paganism & druidry',
  'VMQ': 'Body, mind & spirit: thought & practice',
  'VMQH': 'Mind, body, spirit: meditation & visualization',
  'VMS': 'Spiritualism',
  'VMT': 'Unexplained mysteries & phenomena',
  'VMTC': 'UFOs & extraterrestrial beings',
  'VMPA': 'Personal awareness & self-help: general',
  'VMPF': 'Assertiveness, motivation & self-esteem',
  'VMPL': 'Advice on careers & achieving success',
  'VS': 'Self-help & personal development',
  'VSB': 'Assertiveness, motivation, self-esteem & positive mental attitude',
  'VSC': 'Popular psychology',
  'VSCP': 'Neuro-linguistic programming (NLP)',
  'VSD': 'Advice on education',
  'VSF': 'Popular & applied psychology',
  'VSG': 'Career guidance',
  'VSH': 'Retirement',
  'VSJA': 'Advice on careers & achieving success',
  'VSJB': 'Starting a business',
  'VSK': 'Advice on careers & achieving success',
  'VSP': 'Personal finance',
  'VSPC': 'Retirement planning',
  'VSR': 'Consumer advice',
  'VSRD': 'Consumer advice: buying a house',
  'VSZ': 'Retirement',
  'W': 'Lifestyle, Sport & Leisure',
  'WB': 'Humour',
  'WBC': 'Humour collections & anthologies',
  'WBQ': 'Parodies & spoofs',
  'WC': 'Travel & holiday',
  'WCB': 'Travel writing',
  'WCG': 'Travel guides: general',
  'WCH': 'Travel guides: holidays',
  'WCM': 'Travel maps & atlases',
  'WCT': 'Travel: general & pictorial',
  'WCV': 'Travel & holiday guides',
  'WD': 'Hobbies, quizzes & games',
  'WDC': 'Indoor games',
  'WDCB': 'Card games',
  'WDCC': 'Board games',
  'WDCG': 'Chess',
  'WDH': 'Hobbies',
  'WDJ': 'Antiques & collectibles: general',
  'WDK': 'Antiques & collectibles: general',
  'WDKF': 'Antiques & collectibles: books, manuscripts, ephemera',
  'WDKP': 'Antiques & collectibles: stamps, coins & banknotes',
  'WDKR': 'Antiques & collectibles: ceramics, glass & china',
  'WDKZ': 'Antiques & collectibles: toys, games & models',
  'WF': 'Handicrafts, decorative arts & crafts',
  'WFB': 'Rural crafts',
  'WFC': 'Needlework & fabric crafts',
  'WFCQ': 'Patchwork & quilting',
  'WFG': 'Flower arranging & floral crafts',
  'WFH': 'Woodwork, carpentry & joinery',
  'WFJ': 'Pottery, ceramics & glass crafts',
  'WFK': 'Paper crafts',
  'WFN': 'Toy making',
  'WFT': 'Handicrafts, decorative arts & crafts: general',
  'WFU': 'Fashion & textiles: design',
  'WFV': 'Fashion & textiles: design, illustration & commercial art',
  'WFZ': 'Wood crafts',
  'WG': 'Transport: general interest',
  'WGC': 'Road & motor vehicles: general interest',
  'WGCF': 'Buses, trams & commercial vehicles',
  'WGCK': 'Tractors & farm vehicles',
  'WGCN': 'Motor cars',
  'WGD': 'Ships & boats: general interest',
  'WGF': 'Trains & railways: general interest',
  'WGG': 'Aircraft: general interest',
  'WGM': 'Bicycles & non-motorized transport: general interest',
  'WH': 'Lifestyle & personal style guides',
  'WHB': 'Fashion & style guides',
  'WHBF': 'Fashion: accessories',
  'WJ': 'Pets',
  'WJC': 'Horses & ponies',
  'WJD': 'Dogs as pets',
  'WJF': 'Cats as pets',
  'WJK': 'Birds as pets',
  'WN': 'Nature & the natural world: general interest',
  'WNC': 'Wildlife: general interest',
  'WNCB': 'Wildlife: birds & birdwatching',
  'WNCK': 'Wildlife: butterflies, insects & spiders',
  'WNCN': 'Wildlife: aquatic creatures',
  'WNCW': 'Trees, wildflowers & plants',
  'WNF': 'Natural history: general',
  'WNJ': 'Dinosaurs & prehistoric world: general interest',
  'WNP': 'Popular science',
  'WNPF': 'Environmental science',
  'WNPG': 'Astronomy & space',
  'WNW': 'Weather & climate: general interest',
  'WQ': 'Local interest, family history & nostalgia',
  'WQH': 'Family history, tracing ancestors',
  'WQL': 'Local history',
  'WQP': 'Places in old photographs',
  'WQY': 'Local interest, nostalgia',
  'WS': 'Stationery & miscellaneous items',
  'WT': 'Graphic novels & Manga',
  'WTM': 'Manga: general',
  'Y': 'Children\'s, Teenage & Educational',
  'YB': 'Children\'s / Teenage fiction & true stories',
  'YBC': 'Picture books, activity books & early learning material',
  'YBCS': 'Picture storybooks',
  'YBG': 'First / early chapter books',
  'YBL': 'Poetry',
  'YBR': 'Romance & relationships stories (Children\'s / Teenage)',
  'YFC': 'Science fiction (Children\'s / Teenage)',
  'YFD': 'Fantasy & magical realism (Children\'s / Teenage)',
  'YFG': 'Detective & mystery stories (Children\'s / Teenage)',
  'YFH': 'Adventure stories (Children\'s / Teenage)',
  'YFJ': 'Horror & ghost stories (Children\'s / Teenage)',
  'YFK': 'Crime & thriller',
  'YFM': 'War & anti-war stories (Children\'s / Teenage)',
  'YFN': 'Traditional stories (Children\'s / Teenage)',
  'YFNB': 'Fairy tales & folktales (Children\'s / Teenage)',
  'YFQ': 'Humorous stories (Children\'s / Teenage)',
  'YFS': 'True stories (Children\'s / Teenage)',
  'YFT': 'Animal stories (Children\'s / Teenage)',
  'YFU': 'Sports stories (Children\'s / Teenage)',
  'YFW': 'Religious & spiritual stories (Children\'s / Teenage)',
  'YFX': 'Historical fiction (Children\'s / Teenage)',
  'YFZ': 'Stories in verse (Children\'s / Teenage)',
  'YN': 'Children\'s / Teenage: general non-fiction',
  'YNA': 'Art & design',
  'YNB': 'People & places',
  'YNBC': 'Biography: general',
  'YNC': 'Social issues',
  'YNCS': 'Personal & social issues',
  'YNDEF': 'Educational: English language: readers & reading schemes',
  'YNF': 'Educational material',
  'YNFN': 'Educational: Sciences, general science',
  'YNG': 'Hobbies, interests & leisure',
  'YNGC': 'Sport & outdoor recreation',
  'YNGL': 'History & the past',
  'YNH': 'Humour & jokes',
  'YNJ': 'Animals & nature',
  'YNJN': 'Natural history',
  'YNK': 'Music',
  'YNM': 'Maths & numeracy',
  'YNP': 'Philosophy, religion & beliefs',
  'YNPC': 'Religion & beliefs',
  'YNPF': 'Social sciences',
  'YNR': 'Transport & vehicles',
  'YNS': 'Science & technology: general',
  'YNTA': 'Technology: general',
  'YNTE': 'Computers & technology',
  'YNTG': 'Earth sciences: general',
  'YNTH': 'The natural world & nature stories',
  'YNU': 'Practical interests',
  'YNUH': 'Cookery, food & drink',
  'YNUL': 'Gardening',
  'YNUM': 'Crafts & hobbies',
  'YNV': 'Reference works',
  'YNVA': 'Atlases & maps',
  'YNVC': 'Dictionaries',
  'YNVE': 'Encyclopaedias',
  'YNVR': 'Study aids & revision guides',
  'YNW': 'Science & technology: general interest',
  'YNWB': 'Biology & zoology',
  'YNWC': 'Chemistry',
  'YNWF': 'The Earth: natural history: general',
  'YNWG': 'Geography',
  'YNWM': 'Mathematics & numeracy',
  'YNWP': 'Physics',
  'YP': 'Educational: textbooks, teaching & learning materials',
  'YPB': 'Educational: languages (other than English)',
  'YPC': 'Educational: English language & literacy',
  'YPD': 'Educational: Mathematics & numeracy',
  'YPG': 'Educational: History',
  'YPH': 'Educational: Geography',
  'YPJ': 'Educational: Sciences, general science',
  'YPM': 'Educational: Music',
  'YPN': 'Educational: Art & design',
  'YPR': 'Educational: religious studies',
  'YPRL': 'Educational: religious studies: Buddhism',
  'YPRM': 'Educational: religious studies: Christianity',
  'YPRN': 'Educational: religious studies: Hinduism',
  'YPRP': 'Educational: religious studies: Islam',
  'YPRQ': 'Educational: religious studies: Judaism',
  'YPS': 'Educational: Social sciences',
  'YPT': 'Educational: technology',
  'YPW': 'Educational: physical education (PE), sports, games & motor skills',
  'YPZ': 'Educational: life skills',
  'YQ': 'Educational resources & study guides',
  'YQA': 'Educational: Arts, general',
  'YQC': 'Educational: English language: literacy & reading schemes',
  'YQCR': 'Educational: English language: readers & reading schemes',
  'YQF': 'Educational: Geography',
  'YQH': 'Educational: History',
  'YQL': 'Educational: Languages other than English',
  'YQM': 'Educational: Mathematics & numeracy',
  'YQR': 'Educational: Religious studies',
  'YQS': 'Educational: Sciences, general science',
  'YQZ': 'Educational: examinations & assessment',
  'YR': 'Reference works (Children\'s / Teenage)',
  'YRD': 'Children\'s / Teenage: reference works: dictionaries',
  'YRE': 'Children\'s / Teenage: reference works: encyclopaedias',
  'YRG': 'Children\'s / Teenage: reference works: atlases & maps',
  'YX': 'Personal & social issues (Children\'s / Teenage)',
  'YXA': 'Personal & social issues: body & health (Children\'s / Teenage)',
  'YXB': 'Personal & social issues: families & family members (Children\'s / Teenage)',
  'YXC': 'Personal & social issues: friends & friendship (Children\'s / Teenage)',
  'YXD': 'Personal & social issues: bullying, violence & abuse (Children\'s / Teenage)',
  'YXE': 'Personal & social issues: disability & special needs (Children\'s / Teenage)',
  'YXF': 'Personal & social issues: racism & multiculturalism (Children\'s / Teenage)',
  'YXG': 'Personal & social issues: drugs & addiction (Children\'s / Teenage)',
  'YXH': 'Personal & social issues: sexuality & relationships (Children\'s / Teenage)',
  'YXK': 'Personal & social issues: death & bereavement (Children\'s / Teenage)',
  'YXL': 'Personal & social issues: divorce, separation, breakdown (Children\'s / Teenage)',
  'YXN': 'Personal & social issues: self-awareness & self-esteem (Children\'s / Teenage)',
  'YXZ': 'Personal & social issues (Children\'s / Teenage): general',
};
