/**
 * Thema International Subject Classification
 * Maps Thema codes to their full descriptive names
 * Thema is the modern successor to BIC, designed for international book trade
 * Auto-generated from thema.csv
 */
export const THEMA_CODES: Record<string, string> = {
  'A': 'The Arts',
  'AB': 'The arts: general topics',
  'ABA': 'Theory of art',
  'ABC': 'Conservation, restoration and care of artworks',
  'ABK': 'Individual artists, art monographs',
  'ABQ': 'Art techniques and principles',
  'AFC': 'Films, cinema',
  'AFCV': 'Film scripts and screenplays',
  'AFD': 'Radio',
  'AFDV': 'Radio scripts and screenplays',
  'AFDX': 'History of radio',
  'AFF': 'Film history, theory and criticism',
  'AFJ': 'Television',
  'AFJV': 'Television scripts and screenplays',
  'AFJX': 'History of television',
  'AFT': 'Television and radio',
  'AG': 'Music',
  'AGA': 'Theory of music and musicology',
  'AGB': 'Musical notation',
  'AGC': 'Music reviews and criticism',
  'AGD': 'Discographies and buyer\'s guides',
  'AGDA': 'Discography: classical music',
  'AGDB': 'Discography: non-classical music',
  'AGH': 'Musical instruments & instrumental ensembles',
  'AGHA': 'Percussion instruments',
  'AGHB': 'String instruments',
  'AGHC': 'Wind instruments',
  'AGHD': 'Keyboard instruments',
  'AGHF': 'Instrumental ensembles',
  'AGHK': 'Electronic instruments',
  'AGHN': 'Mechanical instruments',
  'AGM': 'Bands, groups & musicians',
  'AGMC': 'Bands and musical groups',
  'AGMD': 'Composers',
  'AGME': 'Conductors',
  'AGML': 'Individual musician',
  'AGMN': 'Singers',
  'AGN': 'Choral music',
  'AGR': 'Religious music and sacred music',
  'AGS': 'Opera',
  'AGT': 'Songs, lyrics, libretti',
  'AGV': 'Vocal music',
  'AGZ': 'Music: techniques and exercises',
  'AJ': 'Photography and photographs',
  'AJB': 'Individual photographers',
  'AJC': 'Photographic equipment and techniques',
  'AJCD': 'Digital photography',
  'AJCP': 'Photographic reportage',
  'AJCR': 'Photographic darkroom techniques',
  'AJCT': 'Photographic reference works',
  'AJG': 'Photographs: collections',
  'AJP': 'Photographs: portraits',
  'AJR': 'Photographs: documentary',
  'AK': 'Design, Industrial and Commercial Art',
  'AKB': 'Individual designers',
  'AKC': 'Graphic design',
  'AKD': 'Typography and lettering',
  'AKH': 'Book design',
  'AKL': 'Illustration and commercial art',
  'AKLB': 'Illustration',
  'AKLC': 'Comic book and cartoon art',
  'AKP': 'Product design',
  'AKPR': 'Car design',
  'AKT': 'Fashion and textiles: design',
  'AM': 'Architecture',
  'AMA': 'Architectural theory',
  'AMB': 'Individual architects and architectural firms',
  'AMC': 'Architectural structure and design',
  'AMCR': 'Architectural practice and management',
  'AMCX': 'History of architecture',
  'AMG': 'Public buildings: civic, commercial, industrial, etc.',
  'AMGC': 'Religious buildings',
  'AMGD': 'Sports and leisure buildings',
  'AMGR': 'Shopping centres and retail stores',
  'AMK': 'Architecture: interior design',
  'AMKD': 'Interior decoration: furniture',
  'AMKH': 'Interior decoration: domestic buildings',
  'AML': 'Landscape art and architecture',
  'AMLB': 'Garden design and planning',
  'AMLC': 'Urban landscape design and planning',
  'AMN': 'Sustainable architecture and green design',
  'AMR': 'Architecture: residential and domestic buildings',
  'AMRD': 'Houses, apartments, flats',
  'AMRK': 'Rural buildings and structures',
  'AMV': 'Architectural: professional practice',
  'AMX': 'Architecture: public, commercial and industrial buildings',
  'AN': 'Art forms',
  'ANA': 'Ancient art',
  'ANAG': 'Art: Ancient Greek',
  'ANAR': 'Art: Ancient Roman',
  'ANC': 'Medieval art',
  'AND': 'Early modern art',
  'ANDF': 'Renaissance art',
  'ANDG': 'Gothic art',
  'ANF': '19th century art',
  'ANG': '20th century and contemporary art',
  'ANGB': 'Modern art',
  'ANGD': 'Postmodern art',
  'ANGH': 'Contemporary art',
  'AT': 'Performing arts',
  'ATC': 'Theatre studies',
  'ATD': 'Theatre direction and production',
  'ATDS': 'Stage design, set design, lighting design',
  'ATF': 'Theatre: technical and background skills',
  'ATH': 'Acting techniques',
  'ATJA': 'Ballet',
  'ATJD': 'Contemporary dance',
  'ATJF': 'Folk dance',
  'ATJH': 'Dance for children',
  'ATJM': 'Modern dance',
  'ATL': 'Theatre: individual actors and performers',
  'ATP': 'Playwriting',
  'ATQ': 'Plays, playscripts',
  'ATQC': 'Plays: classical, early & medieval',
  'ATQD': 'Plays: from c 1500 to c 1900',
  'ATQE': 'Plays: from c 1900 onwards',
  'ATQF': 'Plays: anthologies',
  'ATQS': 'Plays: Shakespeare',
  'ATV': 'Dance',
  'AVA': 'Electronic, holographic and video art',
  'AVJ': 'Artists\' books',
  'AVL': 'Street art and graffiti',
  'AVP': 'Performance art',
  'AVQ': 'Body art and tattooing',
  'B': 'Biography, Literature & Literary Studies',
  'BG': 'Biography: general',
  'BGA': 'Autobiography: general',
  'BGB': 'Biography: business and industry',
  'BGF': 'Biography: historical, political & military',
  'BGFA': 'Biography: royalty',
  'BGFF': 'Biography: adventurers & explorers',
  'BGFH': 'Biography: historical',
  'BGFP': 'Biography: political',
  'BGH': 'Biography: religious and spiritual',
  'BGL': 'Biography: literary',
  'BGM': 'Memoirs',
  'BGR': 'Biography: science, technology & medicine',
  'BGRA': 'Biography: scientists, technologists & engineers',
  'BGRB': 'Biography: mathematicians',
  'BGRL': 'Biography: medical practitioners',
  'BGS': 'Biography: sport',
  'BGT': 'Biography: arts & entertainment',
  'BGTA': 'Biography: actors & entertainers',
  'BGTC': 'Biography: composers & musicians',
  'BGTD': 'Biography: dancers',
  'BGTF': 'Biography: film, television',
  'BGTP': 'Biography: artists, architects & photographers',
  'BGX': 'Autobiography: arts & entertainment',
  'BGXA': 'Autobiography: actors & entertainers',
  'BGXC': 'Autobiography: composers & musicians',
  'BGXD': 'Autobiography: dancers',
  'BGXF': 'Autobiography: film, television',
  'BGXP': 'Autobiography: artists, architects & photographers',
  'BJ': 'Diaries, letters & journals',
  'BJF': 'Letters (correspondence)',
  'BJH': 'Journals (diaries)',
  'BJN': 'Collected biographies',
  'BK': 'Essays',
  'BKL': 'Literary essays',
  'BM': 'General and world literature: collections and anthologies',
  'BN': 'Literature: history and criticism',
  'BNA': 'Literary studies: general',
  'BNAC': 'Literary theory',
  'BNAX': 'Literary studies: from c 1900 to c 2000',
  'BNB': 'Literary studies: classical, early & medieval',
  'BNBA': 'Literary studies: classical',
  'BNBC': 'Literary studies: medieval',
  'BNC': 'Literary studies: c 1500 to c 1800',
  'BNCA': 'Literary studies: c 1500 to c 1800: Shakespeare studies',
  'BND': 'Literary studies: c 1800 to c 1900',
  'BNF': 'Literary studies: from c 2000',
  'BNH': 'Literary studies: fiction, novelists & prose writers',
  'BNHF': 'Crime & mystery fiction',
  'BNHG': 'Horror & ghost fiction',
  'BNHP': 'Science fiction',
  'BNHR': 'Romance fiction',
  'BNK': 'Literary studies: plays & playwrights',
  'BNKP': 'Shakespeare studies',
  'BNM': 'Literary studies: poetry & poets',
  'BNP': 'Literary studies: literary essay',
  'BNR': 'Literary reference works',
  'BNRC': 'Dictionaries of literature',
  'BNRE': 'Encyclopaedias of literature',
  'BNRX': 'Literary studies: anthologies',
  'BNT': 'Literature: history & criticism: specific literary movements',
  'BNTM': 'Modernism',
  'BNTP': 'Postmodernism',
  'BNTS': 'Structuralism',
  'BNV': 'Literature of other lands: authors & works',
  'BNVA': 'Classic fiction (pre c 1945)',
  'BNVF': 'Modern fiction',
  'BNVL': 'Translation & interpretation',
  'C': 'Language and Linguistics',
  'CB': 'Language: reference & general',
  'CBA': 'General & world languages: history & criticism',
  'CBAH': 'Historical & comparative linguistics',
  'CBAL': 'Linguistic theories',
  'CBAS': 'Semantics, discourse analysis, etc',
  'CBD': 'Dictionaries',
  'CBDX': 'Bilingual & multilingual dictionaries',
  'CBF': 'Thesauruses',
  'CBG': 'Grammar, syntax & morphology',
  'CBGN': 'Historical & comparative grammar',
  'CBGS': 'Syntax',
  'CBGT': 'Morphology',
  'CBP': 'Phonetics, phonology',
  'CBV': 'Writing & editing guides',
  'CBW': 'Creative writing & creative writing guides',
  'CBX': 'Language teaching & learning',
  'CBXL': 'Language teaching theory & methods',
  'CF': 'Linguistics',
  'CFA': 'Philosophy of language',
  'CFB': 'Sociolinguistics',
  'CFC': 'Literacy',
  'CFD': 'Psycholinguistics and cognitive linguistics',
  'CFG': 'Semantics, discourse analysis, stylistics',
  'CFGA': 'Semantics',
  'CFGD': 'Discourse analysis',
  'CFGS': 'Stylistics',
  'CFH': 'Historical & comparative linguistics',
  'CFK': 'Language: origins & general works',
  'CFL': 'Palaeography (history of writing)',
  'CFM': 'Lexicography',
  'CFP': 'Phonetics, phonology',
  'CFX': 'Computational linguistics / Corpus linguistics',
  'CJ': 'Language teaching & learning',
  'CJA': 'English language teaching (ELT)',
  'CJAB': 'ELT: learning material & coursework',
  'CJAC': 'ELT: grammar, vocabulary & pronunciation',
  'CJAG': 'ELT: background & reference material',
  'CJAK': 'ELT for specific purposes',
  'CJB': 'Language teaching & learning other than ELT',
  'CJBG': 'Language teaching theory & methods',
  'CJBT': 'Language learning: specific skills',
  'CJBV': 'Language learning: readers',
  'CJC': 'Language self-study books',
  'CJP': 'Language phrasebooks',
  'D': 'Biography, Literature & Literary Studies',
  'DC': 'Poetry',
  'DCF': 'Poetry by individual poets',
  'DCQ': 'Poetry anthologies (various poets)',
  'DD': 'Plays, playscripts',
  'DDA': 'Plays: Shakespeare',
  'DDC': 'Plays: from c 1900 -',
  'DN': 'Prose: non-fiction',
  'DNB': 'Biography & autobiography',
  'DNF': 'Reportage & collected journalism',
  'DNJ': 'Diaries, letters & journals',
  'DNX': 'Anthologies (non-poetry)',
  'DS': 'Literature: history & criticism',
  'DSA': 'Literary studies: general',
  'DSB': 'Literary studies: classical, early & medieval',
  'DSC': 'Literary studies: c 1500 to c 1800',
  'DSD': 'Literary studies: c 1800 to c 1900',
  'DSG': 'Literary studies: plays & playwrights',
  'DSK': 'Literary studies: fiction, novelists & prose writers',
  'DSR': 'Literary studies: poetry & poets',
  'DSY': 'Children\'s, young adult & educational literature',
  'F': 'Fiction and Related Items',
  'FA': 'Modern & contemporary fiction',
  'FB': 'Thriller / suspense fiction',
  'FBC': 'Crime & mystery fiction',
  'FC': 'Historical fiction',
  'FD': 'Adventure fiction',
  'FF': 'Horror & supernatural fiction',
  'FG': 'Western fiction',
  'FH': 'Humorous fiction',
  'FJ': 'Fantasy',
  'FJD': 'Dark fantasy',
  'FJG': 'Epic fantasy',
  'FJM': 'Contemporary fantasy',
  'FJP': 'Paranormal romance',
  'FJV': 'Urban fantasy',
  'FK': 'Science fiction',
  'FKA': 'Alien contact',
  'FKD': 'Dystopian & utopian fiction',
  'FKL': 'Time travel fiction',
  'FKM': 'Space opera',
  'FKP': 'Near-future science fiction',
  'FKS': 'Military science fiction',
  'FKW': 'Steampunk',
  'FL': 'Horror & ghost stories',
  'FM': 'Romance',
  'FMR': 'Contemporary romance',
  'FMX': 'Historical romance',
  'FP': 'Erotic fiction',
  'FR': 'Religious & spiritual fiction',
  'FT': 'Sagas',
  'FU': 'Speculative fiction',
  'FV': 'War & combat fiction',
  'FW': 'Adventure / action fiction',
  'FX': 'Fiction: narrative themes',
  'FXC': 'Coming-of-age fiction',
  'FXD': 'Domestic fiction',
  'FXL': 'Psychological fiction',
  'FXR': 'Relationship fiction',
  'FXS': 'Espionage & spy fiction',
  'FY': 'Classic fiction',
  'FYB': 'Biographical fiction',
  'FYH': 'Historical fiction',
  'FYT': 'Myth & legend told as fiction',
  'FZ': 'Fiction: related items',
  'FZA': 'Literary studies: fiction, novelists & prose writers',
  'FZM': 'TV, movie, game tie-in fiction',
  'G': 'Reference, Information and Interdisciplinary Subjects',
  'GB': 'Encyclopaedias & reference works',
  'GBC': 'Encyclopaedias',
  'GBD': 'Dictionaries',
  'GBF': 'Directories & annuals',
  'GBP': 'Atlases & maps',
  'GT': 'Interdisciplinary studies',
  'GTC': 'Communication studies',
  'GTD': 'Development studies',
  'GTF': 'Peace studies & conflict resolution',
  'GTM': 'Regional studies',
  'GTP': 'Area studies',
  'GTR': 'General studies',
  'GTT': 'Study & learning skills: general',
  'GTV': 'Environmental sciences',
  'GTZ': 'Research methods: general',
  'H': 'Humanities',
  'HB': 'History',
  'HBA': 'History: theory & methods',
  'HBAH': 'Historiography',
  'HBAZ': 'History: reference works',
  'HBG': 'General & world history',
  'HBGO': 'Oral history',
  'HBGZ': 'World history: from c 1900 to c 1945',
  'HBJ': 'Regional & national history',
  'HBJD': 'European history',
  'HBJF': 'Asian history',
  'HBJH': 'African history',
  'HBJK': 'History of the Americas',
  'HBJM': 'Middle Eastern history',
  'HBJN': 'Australasian & Pacific history',
  'HBL': 'History: earliest times to present day',
  'HBLA': 'Ancient history',
  'HBLB': 'Classical history / classical civilisation',
  'HBLC': 'Early history: c 500 to c 1450/1500',
  'HBLF': 'Early modern history: c 1450/1500 to c 1700',
  'HBLH': 'Modern history to 20th century: c 1700 to c 1900',
  'HBLJ': '19th century history: c 1800 to c 1900',
  'HBLL': '20th century history: c 1900 to c 2000',
  'HBLW': '21st century history: from c 2000 -',
  'HBT': 'History: specific events & topics',
  'HBTB': 'Social & cultural history',
  'HBTD': 'Oral history',
  'HBTF': 'Family history, tracing ancestors',
  'HBTG': 'Historical geography',
  'HBTH': 'Economic history',
  'HBTJ': 'Industrial history',
  'HBTK': 'Military history',
  'HBTN': 'History of specific subjects',
  'HBTP': 'Historical maps & atlases',
  'HBTR': 'National liberation & independence, post-colonialism',
  'HBTS': 'Slavery & abolition of slavery',
  'HBTV': 'Revolutions, uprisings, rebellions',
  'HBTW': 'Revolutionary groups & movements',
  'HBTZ': 'Genocide & ethnic cleansing',
  'HBW': 'Military history',
  'HBWB': 'Land warfare',
  'HBWD': 'Naval warfare',
  'HBWF': 'Air warfare',
  'HBWH': 'Weapons & equipment',
  'HBWK': 'Prisoners of war',
  'HBWM': 'Strategy, tactics',
  'HBWN': 'Military history: specific wars & campaigns',
  'HBWP': 'Military history: post-WW2 conflicts',
  'HBWQ': 'Military history: World Wars',
  'HBWS': 'Military history: battles & campaigns',
  'HBX': 'History: other',
};
