export const ERRORS = {
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_URL: 'Invalid URL',
  EMAIL_REQUIRED: 'Email is required',
  PASSWORD_REQUIRED: 'Password is required',
  TITLE_REQUIRED: 'errors.titleRequired',
  URL_REQUIRED: 'URL is required',
  IMPRINT_REQUIRED: 'Imprint is required',
  WORK_TYPE_REQUIRED: 'Work Type is required',
  COPYRIGHT_HOLDER_REQUIRED: 'Copyright holder is required',
  WORK_STATUS_REQUIRED: 'Work Status is required',
  CONTRIBUTOR_TYPE_REQUIRED: 'Contributor Type is required',
  MAX_FILE_SIZE_EXCEEDED: 'Max file size exceeded',
  MIN_FILE_SIZE_NOT_MET: 'Min file size not met',
  FILE_FORMAT_INVALID: 'File format is invalid',
  COVER_IMAGE_MUST_BE_JPEG: 'coverImageMustBeJpeg',
  TITLE_LANGUAGE_REQUIRED: 'Title Language is required',
  DOI_IS_REQUIRED: 'DOI is required',
  XML_PARSING_ERROR: 'errors.xmlParsingError',
  CSV_PARSING_ERROR: 'errors.csvParsingError',
} as const;
