export const ERRORS = {
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_URL: 'Invalid URL',
  EMAIL_REQUIRED: 'Email is required',
  PASSWORD_REQUIRED: 'Password is required',
  TITLE_REQUIRED: 'Title is required',
  URL_REQUIRED: 'URL is required',
  IMPRINT_REQUIRED: 'Imprint is required',
  WORK_TYPE_REQUIRED: 'Work Type is required',
  COPYRIGHT_HOLDER_REQUIRED: 'Copyright holder is required',
  WORK_STATUS_REQUIRED: 'Work Status is required',
  CONTRIBUTOR_TYPE_REQUIRED: 'Contributor Type is required',
  MAX_FILE_SIZE_EXCEEDED: 'Max file size exceeded',
  FILE_FORMAT_INVALID: 'File format is invalid',
  TITLE_LANGUAGE_REQUIRED: 'Title Language is required',
} as const;
