import { ERRORS, WorkStatuses, WorkTypes } from '@/src/shared/constants';

import { convertFormFieldsToSelectFieldOptions } from '../utils';

const {
  EMAIL_REQUIRED,
  PASSWORD_REQUIRED,
  TITLE_REQUIRED,
  URL_REQUIRED,
  IMPRINT_REQUIRED,
  WORK_TYPE_REQUIRED,
  COPYRIGHT_HOLDER_REQUIRED,
  WORK_STATUS_REQUIRED,
} = ERRORS;

export const InputTypes = {
  EMAIL: 'email',
  PASSWORD: 'password',
  TEXT: 'text',
  URL: 'url',
  NUMBER: 'number',
} as const;

export const FORM_FIELDS = {
  EMAIL: {
    label: 'Email',
    name: 'email',
    placeholder: 'Email',
    errorMessage: EMAIL_REQUIRED,
    type: InputTypes.EMAIL,
  },
  PASSWORD: {
    label: 'Password',
    name: 'password',
    placeholder: 'Password',
    errorMessage: PASSWORD_REQUIRED,
    type: InputTypes.PASSWORD,
  },
  TITLE: {
    label: 'Title',
    name: 'title',
    placeholder: 'Title',
    errorMessage: TITLE_REQUIRED,
    type: InputTypes.TEXT,
    defaultValue: '',
  },
  LICENSE: {
    label: 'License',
    name: 'license',
    placeholder: 'URL',
    errorMessage: URL_REQUIRED,
    type: InputTypes.URL,
    defaultValue: '',
  },
  LANDING_PAGE: {
    label: 'Landing Page URL',
    name: 'landingPage',
    placeholder: 'URL',
    errorMessage: URL_REQUIRED,
    type: InputTypes.URL,
  },
  IMPRINT: {
    label: 'Imprint',
    name: 'imprintId',
    placeholder: 'Imprint',
    errorMessage: IMPRINT_REQUIRED,
    defaultValue: '',
  },
  WORK_TYPE: {
    label: 'Work Type',
    name: 'workType',
    placeholder: 'Work Type',
    errorMessage: WORK_TYPE_REQUIRED,
    defaultValue: '',
  },
  COPYRIGHT_HOLDER: {
    label: 'Copyright holder',
    name: 'copyrightHolder',
    placeholder: 'Copyright holder',
    errorMessage: COPYRIGHT_HOLDER_REQUIRED,
    type: InputTypes.TEXT,
  },
  WORK_STATUS: {
    label: 'Work Status',
    name: 'workStatus',
    placeholder: 'Work Status',
    errorMessage: WORK_STATUS_REQUIRED,
    type: InputTypes.TEXT,
  },
  PUBLICATION_DATE: {
    label: 'Publication Date',
    name: 'publicationDate',
    placeholder: 'Publication Date',
  },
  WORK_TITLE: {
    label: 'Title',
    name: 'workTitle',
    placeholder: 'Title',
    type: InputTypes.TEXT,
  },
  EDITION: {
    label: 'Edition',
    name: 'edition',
    placeholder: 'Edition',
    type: InputTypes.NUMBER,
  },
  COVER_URL: {
    label: 'Cover URL',
    name: 'coverUrl',
    placeholder: 'Cover URL',
    type: InputTypes.URL,
  },
  // FIRST_NAME: 'firstName',
  // LAST_NAME: 'lastName',
  // FULL_NAME: 'fullName',
  // SHORT_NAME: 'shortName',
  // NAME: 'name',
  // WEBSITE_URL: 'websiteUrl',
  // URL: 'url',
  // DESCRIPTION: 'description',
  // SERIES_TYPE: 'seriesType',
  // PUBLICATION_TYPE: 'publicationType',
  // DOI: 'doi',
  // ORCID: 'orcid',
  // ROLE: 'role',
  // CREATED_AT: 'createdAt',
  // UPDATED_AT: 'updatedAt',
  // ISSN_PRINT: 'isnnPrint',
  // ISSN_DIGITAL: 'isnnDigital',
  // PAGE_BREAKDOWN: 'pageBreakdown',
  // COUNTRY_CODE: 'countryCode',
} as const;

export const workTypeOptions = convertFormFieldsToSelectFieldOptions(WorkTypes.options);

export const workStatusOptions = convertFormFieldsToSelectFieldOptions(WorkStatuses.options);

export const licenseOptions = [
  { label: 'CC BY', value: 'https://creativecommons.org/licenses/by/4.0/' },
  { label: 'CC BY-SA', value: 'https://creativecommons.org/licenses/by-sa/4.0/' },
  { label: 'CC BY-ND', value: 'https://creativecommons.org/licenses/by-nd/4.0/' },
  { label: 'CC BY-NC', value: 'https://creativecommons.org/licenses/by-nc/4.0/' },
  { label: 'CC BY-NC-SA', value: 'https://creativecommons.org/licenses/by-nc-sa/4.0/' },
  { label: 'CC BY-NC-ND', value: 'https://creativecommons.org/licenses/by-nc-nd/4.0/' },
  { label: 'CC0', value: 'https://creativecommons.org/publicdomain/zero/1.0/' },
  { label: 'Public Domain', value: 'https://creativecommons.org/publicdomain/mark/1.0/' },
  { label: 'CC BY 1.0', value: 'https://creativecommons.org/licenses/by/1.0/' },
  { label: 'CC BY-SA 1.0', value: 'https://creativecommons.org/licenses/by-sa/1.0/' },
  { label: 'CC BY-ND 1.0', value: 'https://creativecommons.org/licenses/by-nd/1.0/' },
  { label: 'CC BY-NC 1.0', value: 'https://creativecommons.org/licenses/by-nc/1.0/' },
  { label: 'CC BY-NC-SA 1.0', value: 'https://creativecommons.org/licenses/by-nc-sa/1.0/' },
  { label: 'CC BY-NC-ND 1.0', value: 'https://creativecommons.org/licenses/by-nc-nd/1.0/' },
  { label: 'CC BY 2.0', value: 'https://creativecommons.org/licenses/by/2.0/' },
  { label: 'CC BY-SA 2.0', value: 'https://creativecommons.org/licenses/by-sa/2.0/' },
  { label: 'CC BY-ND 2.0', value: 'https://creativecommons.org/licenses/by-nd/2.0/' },
  { label: 'CC BY-NC 2.0', value: 'https://creativecommons.org/licenses/by-nc/2.0/' },
  { label: 'CC BY-NC-SA 2.0', value: 'https://creativecommons.org/licenses/by-nc-sa/2.0/' },
  { label: 'CC BY-NC-ND 2.0', value: 'https://creativecommons.org/licenses/by-nc-nd/2.0/' },
  { label: 'CC BY 2.5', value: 'https://creativecommons.org/licenses/by/2.5/' },
  { label: 'CC BY-SA 2.5', value: 'https://creativecommons.org/licenses/by-sa/2.5/' },
  { label: 'CC BY-ND 2.5', value: 'https://creativecommons.org/licenses/by-nd/2.5/' },
  { label: 'CC BY-NC 2.5', value: 'https://creativecommons.org/licenses/by-nc/2.5/' },
  { label: 'CC BY-NC-SA 2.5', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/' },
  { label: 'CC BY-NC-ND 2.5', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/' },
  { label: 'CC BY 3.0', value: 'https://creativecommons.org/licenses/by/3.0/' },
  { label: 'CC BY-SA 3.0', value: 'https://creativecommons.org/licenses/by-sa/3.0/' },
  { label: 'CC BY-ND 3.0', value: 'https://creativecommons.org/licenses/by-nd/3.0/' },
  { label: 'CC BY-NC 3.0', value: 'https://creativecommons.org/licenses/by-nc/3.0/' },
  { label: 'CC BY-NC-SA 3.0', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/' },
  { label: 'CC BY-NC-ND 3.0', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/' },
  { label: 'CC BY 2.5 AR', value: 'https://creativecommons.org/licenses/by/2.5/ar/' },
  { label: 'CC BY-SA 2.5 AR', value: 'https://creativecommons.org/licenses/by-sa/2.5/ar/' },
  { label: 'CC BY-ND 2.5 AR', value: 'https://creativecommons.org/licenses/by-nd/2.5/ar/' },
  { label: 'CC BY-NC 2.5 AR', value: 'https://creativecommons.org/licenses/by-nc/2.5/ar/' },
  { label: 'CC BY-NC-SA 2.5 AR', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/ar/' },
  { label: 'CC BY-NC-ND 2.5 AR', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/ar/' },
  { label: 'CC BY 2.5 AU', value: 'https://creativecommons.org/licenses/by/2.5/au/' },
  { label: 'CC BY-SA 2.5 AU', value: 'https://creativecommons.org/licenses/by-sa/2.5/au/' },
  { label: 'CC BY-ND 2.5 AU', value: 'https://creativecommons.org/licenses/by-nd/2.5/au/' },
  { label: 'CC BY-NC 2.5 AU', value: 'https://creativecommons.org/licenses/by-nc/2.5/au/' },
  { label: 'CC BY-NC-SA 2.5 AU', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/au/' },
  { label: 'CC BY-NC-ND 2.5 AU', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/au/' },
  { label: 'CC BY 2.5 AT', value: 'https://creativecommons.org/licenses/by/2.5/at/' },
  { label: 'CC BY-SA 2.5 AT', value: 'https://creativecommons.org/licenses/by-sa/2.5/at/' },
  { label: 'CC BY-ND 2.5 AT', value: 'https://creativecommons.org/licenses/by-nd/2.5/at/' },
  { label: 'CC BY-NC 2.5 AT', value: 'https://creativecommons.org/licenses/by-nc/2.5/at/' },
  { label: 'CC BY-NC-SA 2.5 AT', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/at/' },
  { label: 'CC BY-NC-ND 2.5 AT', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/at/' },
  { label: 'CC BY 2.5 BE', value: 'https://creativecommons.org/licenses/by/2.5/be/' },
  { label: 'CC BY-SA 2.5 BE', value: 'https://creativecommons.org/licenses/by-sa/2.5/be/' },
  { label: 'CC BY-ND 2.5 BE', value: 'https://creativecommons.org/licenses/by-nd/2.5/be/' },
  { label: 'CC BY-NC 2.5 BE', value: 'https://creativecommons.org/licenses/by-nc/2.5/be/' },
  { label: 'CC BY-NC-SA 2.5 BE', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/be/' },
  { label: 'CC BY-NC-ND 2.5 BE', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/be/' },
  { label: 'CC BY 2.5 BR', value: 'https://creativecommons.org/licenses/by/2.5/br/' },
  { label: 'CC BY-SA 2.5 BR', value: 'https://creativecommons.org/licenses/by-sa/2.5/br/' },
  { label: 'CC BY-ND 2.5 BR', value: 'https://creativecommons.org/licenses/by-nd/2.5/br/' },
  { label: 'CC BY-NC 2.5 BR', value: 'https://creativecommons.org/licenses/by-nc/2.5/br/' },
  { label: 'CC BY-NC-SA 2.5 BR', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/br/' },
  { label: 'CC BY-NC-ND 2.5 BR', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/br/' },
  { label: 'CC BY 2.5 CA', value: 'https://creativecommons.org/licenses/by/2.5/ca/' },
  { label: 'CC BY-SA 2.5 CA', value: 'https://creativecommons.org/licenses/by-sa/2.5/ca/' },
  { label: 'CC BY-ND 2.5 CA', value: 'https://creativecommons.org/licenses/by-nd/2.5/ca/' },
  { label: 'CC BY-NC 2.5 CA', value: 'https://creativecommons.org/licenses/by-nc/2.5/ca/' },
  { label: 'CC BY-NC-SA 2.5 CA', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/ca/' },
  { label: 'CC BY-NC-ND 2.5 CA', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/ca/' },
  { label: 'CC BY 2.5 CL', value: 'https://creativecommons.org/licenses/by/2.5/cl/' },
  { label: 'CC BY-SA 2.5 CL', value: 'https://creativecommons.org/licenses/by-sa/2.5/cl/' },
  { label: 'CC BY-ND 2.5 CL', value: 'https://creativecommons.org/licenses/by-nd/2.5/cl/' },
  { label: 'CC BY-NC 2.5 CL', value: 'https://creativecommons.org/licenses/by-nc/2.5/cl/' },
  { label: 'CC BY-NC-SA 2.5 CL', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/cl/' },
  { label: 'CC BY-NC-ND 2.5 CL', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/cl/' },
  { label: 'CC BY 2.5 CN', value: 'https://creativecommons.org/licenses/by/2.5/cn/' },
  { label: 'CC BY-SA 2.5 CN', value: 'https://creativecommons.org/licenses/by-sa/2.5/cn/' },
  { label: 'CC BY-ND 2.5 CN', value: 'https://creativecommons.org/licenses/by-nd/2.5/cn/' },
  { label: 'CC BY-NC 2.5 CN', value: 'https://creativecommons.org/licenses/by-nc/2.5/cn/' },
  { label: 'CC BY-NC-SA 2.5 CN', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/cn/' },
  { label: 'CC BY-NC-ND 2.5 CN', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/cn/' },
  { label: 'CC BY 2.5 CO', value: 'https://creativecommons.org/licenses/by/2.5/co/' },
  { label: 'CC BY-SA 2.5 CO', value: 'https://creativecommons.org/licenses/by-sa/2.5/co/' },
  { label: 'CC BY-ND 2.5 CO', value: 'https://creativecommons.org/licenses/by-nd/2.5/co/' },
  { label: 'CC BY-NC 2.5 CO', value: 'https://creativecommons.org/licenses/by-nc/2.5/co/' },
  { label: 'CC BY-NC-SA 2.5 CO', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/co/' },
  { label: 'CC BY-NC-ND 2.5 CO', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/co/' },
  { label: 'CC BY 2.5 CZ', value: 'https://creativecommons.org/licenses/by/2.5/cz/' },
  { label: 'CC BY-SA 2.5 CZ', value: 'https://creativecommons.org/licenses/by-sa/2.5/cz/' },
  { label: 'CC BY-ND 2.5 CZ', value: 'https://creativecommons.org/licenses/by-nd/2.5/cz/' },
  { label: 'CC BY-NC 2.5 CZ', value: 'https://creativecommons.org/licenses/by-nc/2.5/cz/' },
  { label: 'CC BY-NC-SA 2.5 CZ', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/cz/' },
  { label: 'CC BY-NC-ND 2.5 CZ', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/cz/' },
  { label: 'CC BY 2.5 DE', value: 'https://creativecommons.org/licenses/by/2.5/de/' },
  { label: 'CC BY-SA 2.5 DE', value: 'https://creativecommons.org/licenses/by-sa/2.5/de/' },
  { label: 'CC BY-ND 2.5 DE', value: 'https://creativecommons.org/licenses/by-nd/2.5/de/' },
  { label: 'CC BY-NC 2.5 DE', value: 'https://creativecommons.org/licenses/by-nc/2.5/de/' },
  { label: 'CC BY-NC-SA 2.5 DE', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/de/' },
  { label: 'CC BY-NC-ND 2.5 DE', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/de/' },
  { label: 'CC BY 2.5 DK', value: 'https://creativecommons.org/licenses/by/2.5/dk/' },
  { label: 'CC BY-SA 2.5 DK', value: 'https://creativecommons.org/licenses/by-sa/2.5/dk/' },
  { label: 'CC BY-ND 2.5 DK', value: 'https://creativecommons.org/licenses/by-nd/2.5/dk/' },
  { label: 'CC BY-NC 2.5 DK', value: 'https://creativecommons.org/licenses/by-nc/2.5/dk/' },
  { label: 'CC BY-NC-SA 2.5 DK', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/dk/' },
  { label: 'CC BY-NC-ND 2.5 DK', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/dk/' },
  { label: 'CC BY 2.5 ES', value: 'https://creativecommons.org/licenses/by/2.5/es/' },
  { label: 'CC BY-SA 2.5 ES', value: 'https://creativecommons.org/licenses/by-sa/2.5/es/' },
  { label: 'CC BY-ND 2.5 ES', value: 'https://creativecommons.org/licenses/by-nd/2.5/es/' },
  { label: 'CC BY-NC 2.5 ES', value: 'https://creativecommons.org/licenses/by-nc/2.5/es/' },
  { label: 'CC BY-NC-SA 2.5 ES', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/es/' },
  { label: 'CC BY-NC-ND 2.5 ES', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/es/' },
  { label: 'CC BY 2.5 FI', value: 'https://creativecommons.org/licenses/by/2.5/fi/' },
  { label: 'CC BY-SA 2.5 FI', value: 'https://creativecommons.org/licenses/by-sa/2.5/fi/' },
  { label: 'CC BY-ND 2.5 FI', value: 'https://creativecommons.org/licenses/by-nd/2.5/fi/' },
  { label: 'CC BY-NC 2.5 FI', value: 'https://creativecommons.org/licenses/by-nc/2.5/fi/' },
  { label: 'CC BY-NC-SA 2.5 FI', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/fi/' },
  { label: 'CC BY-NC-ND 2.5 FI', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/fi/' },
  { label: 'CC BY 2.5 FR', value: 'https://creativecommons.org/licenses/by/2.5/fr/' },
  { label: 'CC BY-SA 2.5 FR', value: 'https://creativecommons.org/licenses/by-sa/2.5/fr/' },
  { label: 'CC BY-ND 2.5 FR', value: 'https://creativecommons.org/licenses/by-nd/2.5/fr/' },
  { label: 'CC BY-NC 2.5 FR', value: 'https://creativecommons.org/licenses/by-nc/2.5/fr/' },
  { label: 'CC BY-NC-SA 2.5 FR', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/fr/' },
  { label: 'CC BY-NC-ND 2.5 FR', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/fr/' },
  { label: 'CC BY 2.5 GB', value: 'https://creativecommons.org/licenses/by/2.5/gb/' },
  { label: 'CC BY-SA 2.5 GB', value: 'https://creativecommons.org/licenses/by-sa/2.5/gb/' },
  { label: 'CC BY-ND 2.5 GB', value: 'https://creativecommons.org/licenses/by-nd/2.5/gb/' },
  { label: 'CC BY-NC 2.5 GB', value: 'https://creativecommons.org/licenses/by-nc/2.5/gb/' },
  { label: 'CC BY-NC-SA 2.5 GB', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/gb/' },
  { label: 'CC BY-NC-ND 2.5 GB', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/gb/' },
  { label: 'CC BY 2.5 GR', value: 'https://creativecommons.org/licenses/by/2.5/gr/' },
  { label: 'CC BY-SA 2.5 GR', value: 'https://creativecommons.org/licenses/by-sa/2.5/gr/' },
  { label: 'CC BY-ND 2.5 GR', value: 'https://creativecommons.org/licenses/by-nd/2.5/gr/' },
  { label: 'CC BY-NC 2.5 GR', value: 'https://creativecommons.org/licenses/by-nc/2.5/gr/' },
  { label: 'CC BY-NC-SA 2.5 GR', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/gr/' },
  { label: 'CC BY-NC-ND 2.5 GR', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/gr/' },
  { label: 'CC BY 2.5 HU', value: 'https://creativecommons.org/licenses/by/2.5/hu/' },
  { label: 'CC BY-SA 2.5 HU', value: 'https://creativecommons.org/licenses/by-sa/2.5/hu/' },
  { label: 'CC BY-ND 2.5 HU', value: 'https://creativecommons.org/licenses/by-nd/2.5/hu/' },
  { label: 'CC BY-NC 2.5 HU', value: 'https://creativecommons.org/licenses/by-nc/2.5/hu/' },
  { label: 'CC BY-NC-SA 2.5 HU', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/hu/' },
  { label: 'CC BY-NC-ND 2.5 HU', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/hu/' },
  { label: 'CC BY 2.5 IE', value: 'https://creativecommons.org/licenses/by/2.5/ie/' },
  { label: 'CC BY-SA 2.5 IE', value: 'https://creativecommons.org/licenses/by-sa/2.5/ie/' },
  { label: 'CC BY-ND 2.5 IE', value: 'https://creativecommons.org/licenses/by-nd/2.5/ie/' },
  { label: 'CC BY-NC 2.5 IE', value: 'https://creativecommons.org/licenses/by-nc/2.5/ie/' },
  { label: 'CC BY-NC-SA 2.5 IE', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/ie/' },
  { label: 'CC BY-NC-ND 2.5 IE', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/ie/' },
  { label: 'CC BY 2.5 IL', value: 'https://creativecommons.org/licenses/by/2.5/il/' },
  { label: 'CC BY-SA 2.5 IL', value: 'https://creativecommons.org/licenses/by-sa/2.5/il/' },
  { label: 'CC BY-ND 2.5 IL', value: 'https://creativecommons.org/licenses/by-nd/2.5/il/' },
  { label: 'CC BY-NC 2.5 IL', value: 'https://creativecommons.org/licenses/by-nc/2.5/il/' },
  { label: 'CC BY-NC-SA 2.5 IL', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/il/' },
  { label: 'CC BY-NC-ND 2.5 IL', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/il/' },
  { label: 'CC BY 2.5 IS', value: 'https://creativecommons.org/licenses/by/2.5/is/' },
  { label: 'CC BY-SA 2.5 IS', value: 'https://creativecommons.org/licenses/by-sa/2.5/is/' },
  { label: 'CC BY-ND 2.5 IS', value: 'https://creativecommons.org/licenses/by-nd/2.5/is/' },
  { label: 'CC BY-NC 2.5 IS', value: 'https://creativecommons.org/licenses/by-nc/2.5/is/' },
  { label: 'CC BY-NC-SA 2.5 IS', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/is/' },
  { label: 'CC BY-NC-ND 2.5 IS', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/is/' },
  { label: 'CC BY 2.5 IT', value: 'https://creativecommons.org/licenses/by/2.5/it/' },
  { label: 'CC BY-SA 2.5 IT', value: 'https://creativecommons.org/licenses/by-sa/2.5/it/' },
  { label: 'CC BY-ND 2.5 IT', value: 'https://creativecommons.org/licenses/by-nd/2.5/it/' },
  { label: 'CC BY-NC 2.5 IT', value: 'https://creativecommons.org/licenses/by-nc/2.5/it/' },
  { label: 'CC BY-NC-SA 2.5 IT', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/it/' },
  { label: 'CC BY-NC-ND 2.5 IT', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/it/' },
  { label: 'CC BY 2.5 JP', value: 'https://creativecommons.org/licenses/by/2.5/jp/' },
  { label: 'CC BY-SA 2.5 JP', value: 'https://creativecommons.org/licenses/by-sa/2.5/jp/' },
  { label: 'CC BY-ND 2.5 JP', value: 'https://creativecommons.org/licenses/by-nd/2.5/jp/' },
  { label: 'CC BY-NC 2.5 JP', value: 'https://creativecommons.org/licenses/by-nc/2.5/jp/' },
  { label: 'CC BY-NC-SA 2.5 JP', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/jp/' },
  { label: 'CC BY-NC-ND 2.5 JP', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/jp/' },
  { label: 'CC BY 2.5 KR', value: 'https://creativecommons.org/licenses/by/2.5/kr/' },
  { label: 'CC BY-SA 2.5 KR', value: 'https://creativecommons.org/licenses/by-sa/2.5/kr/' },
  { label: 'CC BY-ND 2.5 KR', value: 'https://creativecommons.org/licenses/by-nd/2.5/kr/' },
  { label: 'CC BY-NC 2.5 KR', value: 'https://creativecommons.org/licenses/by-nc/2.5/kr/' },
  { label: 'CC BY-NC-SA 2.5 KR', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/kr/' },
  { label: 'CC BY-NC-ND 2.5 KR', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/kr/' },
  { label: 'CC BY 2.5 LU', value: 'https://creativecommons.org/licenses/by/2.5/lu/' },
  { label: 'CC BY-SA 2.5 LU', value: 'https://creativecommons.org/licenses/by-sa/2.5/lu/' },
  { label: 'CC BY-ND 2.5 LU', value: 'https://creativecommons.org/licenses/by-nd/2.5/lu/' },
  { label: 'CC BY-NC 2.5 LU', value: 'https://creativecommons.org/licenses/by-nc/2.5/lu/' },
  { label: 'CC BY-NC-SA 2.5 LU', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/lu/' },
  { label: 'CC BY-NC-ND 2.5 LU', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/lu/' },
  { label: 'CC BY 2.5 MX', value: 'https://creativecommons.org/licenses/by/2.5/mx/' },
  { label: 'CC BY-SA 2.5 MX', value: 'https://creativecommons.org/licenses/by-sa/2.5/mx/' },
  { label: 'CC BY-ND 2.5 MX', value: 'https://creativecommons.org/licenses/by-nd/2.5/mx/' },
  { label: 'CC BY-NC 2.5 MX', value: 'https://creativecommons.org/licenses/by-nc/2.5/mx/' },
  { label: 'CC BY-NC-SA 2.5 MX', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/mx/' },
  { label: 'CC BY-NC-ND 2.5 MX', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/mx/' },
  { label: 'CC BY 2.5 NL', value: 'https://creativecommons.org/licenses/by/2.5/nl/' },
  { label: 'CC BY-SA 2.5 NL', value: 'https://creativecommons.org/licenses/by-sa/2.5/nl/' },
  { label: 'CC BY-ND 2.5 NL', value: 'https://creativecommons.org/licenses/by-nd/2.5/nl/' },
  { label: 'CC BY-NC 2.5 NL', value: 'https://creativecommons.org/licenses/by-nc/2.5/nl/' },
  { label: 'CC BY-NC-SA 2.5 NL', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/nl/' },
  { label: 'CC BY-NC-ND 2.5 NL', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/nl/' },
  { label: 'CC BY 2.5 NZ', value: 'https://creativecommons.org/licenses/by/2.5/nz/' },
  { label: 'CC BY-SA 2.5 NZ', value: 'https://creativecommons.org/licenses/by-sa/2.5/nz/' },
  { label: 'CC BY-ND 2.5 NZ', value: 'https://creativecommons.org/licenses/by-nd/2.5/nz/' },
  { label: 'CC BY-NC 2.5 NZ', value: 'https://creativecommons.org/licenses/by-nc/2.5/nz/' },
  { label: 'CC BY-NC-SA 2.5 NZ', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/nz/' },
  { label: 'CC BY-NC-ND 2.5 NZ', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/nz/' },
  { label: 'CC BY 2.5 NO', value: 'https://creativecommons.org/licenses/by/2.5/no/' },
  { label: 'CC BY-SA 2.5 NO', value: 'https://creativecommons.org/licenses/by-sa/2.5/no/' },
  { label: 'CC BY-ND 2.5 NO', value: 'https://creativecommons.org/licenses/by-nd/2.5/no/' },
  { label: 'CC BY-NC 2.5 NO', value: 'https://creativecommons.org/licenses/by-nc/2.5/no/' },
  { label: 'CC BY-NC-SA 2.5 NO', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/no/' },
  { label: 'CC BY-NC-ND 2.5 NO', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/no/' },
  { label: 'CC BY 2.5 PE', value: 'https://creativecommons.org/licenses/by/2.5/pe/' },
  { label: 'CC BY-SA 2.5 PE', value: 'https://creativecommons.org/licenses/by-sa/2.5/pe/' },
  { label: 'CC BY-ND 2.5 PE', value: 'https://creativecommons.org/licenses/by-nd/2.5/pe/' },
  { label: 'CC BY-NC 2.5 PE', value: 'https://creativecommons.org/licenses/by-nc/2.5/pe/' },
  { label: 'CC BY-NC-SA 2.5 PE', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/pe/' },
  { label: 'CC BY-NC-ND 2.5 PE', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/pe/' },
  { label: 'CC BY 2.5 PL', value: 'https://creativecommons.org/licenses/by/2.5/pl/' },
  { label: 'CC BY-SA 2.5 PL', value: 'https://creativecommons.org/licenses/by-sa/2.5/pl/' },
  { label: 'CC BY-ND 2.5 PL', value: 'https://creativecommons.org/licenses/by-nd/2.5/pl/' },
  { label: 'CC BY-NC 2.5 PL', value: 'https://creativecommons.org/licenses/by-nc/2.5/pl/' },
  { label: 'CC BY-NC-SA 2.5 PL', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/pl/' },
  { label: 'CC BY-NC-ND 2.5 PL', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/pl/' },
  { label: 'CC BY 2.5 PT', value: 'https://creativecommons.org/licenses/by/2.5/pt/' },
  { label: 'CC BY-SA 2.5 PT', value: 'https://creativecommons.org/licenses/by-sa/2.5/pt/' },
  { label: 'CC BY-ND 2.5 PT', value: 'https://creativecommons.org/licenses/by-nd/2.5/pt/' },
  { label: 'CC BY-NC 2.5 PT', value: 'https://creativecommons.org/licenses/by-nc/2.5/pt/' },
  { label: 'CC BY-NC-SA 2.5 PT', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/pt/' },
  { label: 'CC BY-NC-ND 2.5 PT', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/pt/' },
  { label: 'CC BY 2.5 RU', value: 'https://creativecommons.org/licenses/by/2.5/ru/' },
  { label: 'CC BY-SA 2.5 RU', value: 'https://creativecommons.org/licenses/by-sa/2.5/ru/' },
  { label: 'CC BY-ND 2.5 RU', value: 'https://creativecommons.org/licenses/by-nd/2.5/ru/' },
  { label: 'CC BY-NC 2.5 RU', value: 'https://creativecommons.org/licenses/by-nc/2.5/ru/' },
  { label: 'CC BY-NC-SA 2.5 RU', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/ru/' },
  { label: 'CC BY-NC-ND 2.5 RU', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/ru/' },
  { label: 'CC BY 2.5 SE', value: 'https://creativecommons.org/licenses/by/2.5/se/' },
  { label: 'CC BY-SA 2.5 SE', value: 'https://creativecommons.org/licenses/by-sa/2.5/se/' },
  { label: 'CC BY-ND 2.5 SE', value: 'https://creativecommons.org/licenses/by-nd/2.5/se/' },
  { label: 'CC BY-NC 2.5 SE', value: 'https://creativecommons.org/licenses/by-nc/2.5/se/' },
  { label: 'CC BY-NC-SA 2.5 SE', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/se/' },
  { label: 'CC BY-NC-ND 2.5 SE', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/se/' },
  { label: 'CC BY 2.5 SG', value: 'https://creativecommons.org/licenses/by/2.5/sg/' },
  { label: 'CC BY-SA 2.5 SG', value: 'https://creativecommons.org/licenses/by-sa/2.5/sg/' },
  { label: 'CC BY-ND 2.5 SG', value: 'https://creativecommons.org/licenses/by-nd/2.5/sg/' },
  { label: 'CC BY-NC 2.5 SG', value: 'https://creativecommons.org/licenses/by-nc/2.5/sg/' },
  { label: 'CC BY-NC-SA 2.5 SG', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/sg/' },
  { label: 'CC BY-NC-ND 2.5 SG', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/sg/' },
  { label: 'CC BY 2.5 TR', value: 'https://creativecommons.org/licenses/by/2.5/tr/' },
  { label: 'CC BY-SA 2.5 TR', value: 'https://creativecommons.org/licenses/by-sa/2.5/tr/' },
  { label: 'CC BY-ND 2.5 TR', value: 'https://creativecommons.org/licenses/by-nd/2.5/tr/' },
  { label: 'CC BY-NC 2.5 TR', value: 'https://creativecommons.org/licenses/by-nc/2.5/tr/' },
  { label: 'CC BY-NC-SA 2.5 TR', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/tr/' },
  { label: 'CC BY-NC-ND 2.5 TR', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/tr/' },
  { label: 'CC BY 2.5 US', value: 'https://creativecommons.org/licenses/by/2.5/us/' },
  { label: 'CC BY-SA 2.5 US', value: 'https://creativecommons.org/licenses/by-sa/2.5/us/' },
  { label: 'CC BY-ND 2.5 US', value: 'https://creativecommons.org/licenses/by-nd/2.5/us/' },
  { label: 'CC BY-NC 2.5 US', value: 'https://creativecommons.org/licenses/by-nc/2.5/us/' },
  { label: 'CC BY-NC-SA 2.5 US', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/us/' },
  { label: 'CC BY-NC-ND 2.5 US', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/us/' },
  { label: 'CC BY 2.5 VE', value: 'https://creativecommons.org/licenses/by/2.5/ve/' },
  { label: 'CC BY-SA 2.5 VE', value: 'https://creativecommons.org/licenses/by-sa/2.5/ve/' },
  { label: 'CC BY-ND 2.5 VE', value: 'https://creativecommons.org/licenses/by-nd/2.5/ve/' },
  { label: 'CC BY-NC 2.5 VE', value: 'https://creativecommons.org/licenses/by-nc/2.5/ve/' },
  { label: 'CC BY-NC-SA 2.5 VE', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/ve/' },
  { label: 'CC BY-NC-ND 2.5 VE', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/ve/' },
  { label: 'CC BY 2.5 ZA', value: 'https://creativecommons.org/licenses/by/2.5/za/' },
  { label: 'CC BY-SA 2.5 ZA', value: 'https://creativecommons.org/licenses/by-sa/2.5/za/' },
  { label: 'CC BY-ND 2.5 ZA', value: 'https://creativecommons.org/licenses/by-nd/2.5/za/' },
  { label: 'CC BY-NC 2.5 ZA', value: 'https://creativecommons.org/licenses/by-nc/2.5/za/' },
  { label: 'CC BY-NC-SA 2.5 ZA', value: 'https://creativecommons.org/licenses/by-nc-sa/2.5/za/' },
  { label: 'CC BY-NC-ND 2.5 ZA', value: 'https://creativecommons.org/licenses/by-nc-nd/2.5/za/' },
  { label: 'CC BY 3.0 AR', value: 'https://creativecommons.org/licenses/by/3.0/ar/' },
  { label: 'CC BY-SA 3.0 AR', value: 'https://creativecommons.org/licenses/by-sa/3.0/ar/' },
  { label: 'CC BY-ND 3.0 AR', value: 'https://creativecommons.org/licenses/by-nd/3.0/ar/' },
  { label: 'CC BY-NC 3.0 AR', value: 'https://creativecommons.org/licenses/by-nc/3.0/ar/' },
  { label: 'CC BY-NC-SA 3.0 AR', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/ar/' },
  { label: 'CC BY-NC-ND 3.0 AR', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/ar/' },
  { label: 'CC BY 3.0 AU', value: 'https://creativecommons.org/licenses/by/3.0/au/' },
  { label: 'CC BY-SA 3.0 AU', value: 'https://creativecommons.org/licenses/by-sa/3.0/au/' },
  { label: 'CC BY-ND 3.0 AU', value: 'https://creativecommons.org/licenses/by-nd/3.0/au/' },
  { label: 'CC BY-NC 3.0 AU', value: 'https://creativecommons.org/licenses/by-nc/3.0/au/' },
  { label: 'CC BY-NC-SA 3.0 AU', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/au/' },
  { label: 'CC BY-NC-ND 3.0 AU', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/au/' },
  { label: 'CC BY 3.0 AT', value: 'https://creativecommons.org/licenses/by/3.0/at/' },
  { label: 'CC BY-SA 3.0 AT', value: 'https://creativecommons.org/licenses/by-sa/3.0/at/' },
  { label: 'CC BY-ND 3.0 AT', value: 'https://creativecommons.org/licenses/by-nd/3.0/at/' },
  { label: 'CC BY-NC 3.0 AT', value: 'https://creativecommons.org/licenses/by-nc/3.0/at/' },
  { label: 'CC BY-NC-SA 3.0 AT', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/at/' },
  { label: 'CC BY-NC-ND 3.0 AT', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/at/' },
  { label: 'CC BY 3.0 BE', value: 'https://creativecommons.org/licenses/by/3.0/be/' },
  { label: 'CC BY-SA 3.0 BE', value: 'https://creativecommons.org/licenses/by-sa/3.0/be/' },
  { label: 'CC BY-ND 3.0 BE', value: 'https://creativecommons.org/licenses/by-nd/3.0/be/' },
  { label: 'CC BY-NC 3.0 BE', value: 'https://creativecommons.org/licenses/by-nc/3.0/be/' },
  { label: 'CC BY-NC-SA 3.0 BE', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/be/' },
  { label: 'CC BY-NC-ND 3.0 BE', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/be/' },
  { label: 'CC BY 3.0 BR', value: 'https://creativecommons.org/licenses/by/3.0/br/' },
  { label: 'CC BY-SA 3.0 BR', value: 'https://creativecommons.org/licenses/by-sa/3.0/br/' },
  { label: 'CC BY-ND 3.0 BR', value: 'https://creativecommons.org/licenses/by-nd/3.0/br/' },
  { label: 'CC BY-NC 3.0 BR', value: 'https://creativecommons.org/licenses/by-nc/3.0/br/' },
  { label: 'CC BY-NC-SA 3.0 BR', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/br/' },
  { label: 'CC BY-NC-ND 3.0 BR', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/br/' },
  { label: 'CC BY 3.0 CA', value: 'https://creativecommons.org/licenses/by/3.0/ca/' },
  { label: 'CC BY-SA 3.0 CA', value: 'https://creativecommons.org/licenses/by-sa/3.0/ca/' },
  { label: 'CC BY-ND 3.0 CA', value: 'https://creativecommons.org/licenses/by-nd/3.0/ca/' },
  { label: 'CC BY-NC 3.0 CA', value: 'https://creativecommons.org/licenses/by-nc/3.0/ca/' },
  { label: 'CC BY-NC-SA 3.0 CA', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/ca/' },
  { label: 'CC BY-NC-ND 3.0 CA', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/ca/' },
  { label: 'CC BY 3.0 CL', value: 'https://creativecommons.org/licenses/by/3.0/cl/' },
  { label: 'CC BY-SA 3.0 CL', value: 'https://creativecommons.org/licenses/by-sa/3.0/cl/' },
  { label: 'CC BY-ND 3.0 CL', value: 'https://creativecommons.org/licenses/by-nd/3.0/cl/' },
  { label: 'CC BY-NC 3.0 CL', value: 'https://creativecommons.org/licenses/by-nc/3.0/cl/' },
  { label: 'CC BY-NC-SA 3.0 CL', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/cl/' },
  { label: 'CC BY-NC-ND 3.0 CL', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/cl/' },
  { label: 'CC BY 3.0 CN', value: 'https://creativecommons.org/licenses/by/3.0/cn/' },
  { label: 'CC BY-SA 3.0 CN', value: 'https://creativecommons.org/licenses/by-sa/3.0/cn/' },
  { label: 'CC BY-ND 3.0 CN', value: 'https://creativecommons.org/licenses/by-nd/3.0/cn/' },
  { label: 'CC BY-NC 3.0 CN', value: 'https://creativecommons.org/licenses/by-nc/3.0/cn/' },
  { label: 'CC BY-NC-SA 3.0 CN', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/cn/' },
  { label: 'CC BY-NC-ND 3.0 CN', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/cn/' },
  { label: 'CC BY 3.0 CO', value: 'https://creativecommons.org/licenses/by/3.0/co/' },
  { label: 'CC BY-SA 3.0 CO', value: 'https://creativecommons.org/licenses/by-sa/3.0/co/' },
  { label: 'CC BY-ND 3.0 CO', value: 'https://creativecommons.org/licenses/by-nd/3.0/co/' },
  { label: 'CC BY-NC 3.0 CO', value: 'https://creativecommons.org/licenses/by-nc/3.0/co/' },
  { label: 'CC BY-NC-SA 3.0 CO', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/co/' },
  { label: 'CC BY-NC-ND 3.0 CO', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/co/' },
  { label: 'CC BY 3.0 CZ', value: 'https://creativecommons.org/licenses/by/3.0/cz/' },
  { label: 'CC BY-SA 3.0 CZ', value: 'https://creativecommons.org/licenses/by-sa/3.0/cz/' },
  { label: 'CC BY-ND 3.0 CZ', value: 'https://creativecommons.org/licenses/by-nd/3.0/cz/' },
  { label: 'CC BY-NC 3.0 CZ', value: 'https://creativecommons.org/licenses/by-nc/3.0/cz/' },
  { label: 'CC BY-NC-SA 3.0 CZ', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/cz/' },
  { label: 'CC BY-NC-ND 3.0 CZ', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/cz/' },
  { label: 'CC BY 3.0 DE', value: 'https://creativecommons.org/licenses/by/3.0/de/' },
  { label: 'CC BY-SA 3.0 DE', value: 'https://creativecommons.org/licenses/by-sa/3.0/de/' },
  { label: 'CC BY-ND 3.0 DE', value: 'https://creativecommons.org/licenses/by-nd/3.0/de/' },
  { label: 'CC BY-NC 3.0 DE', value: 'https://creativecommons.org/licenses/by-nc/3.0/de/' },
  { label: 'CC BY-NC-SA 3.0 DE', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/de/' },
  { label: 'CC BY-NC-ND 3.0 DE', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/de/' },
  { label: 'CC BY 3.0 DK', value: 'https://creativecommons.org/licenses/by/3.0/dk/' },
  { label: 'CC BY-SA 3.0 DK', value: 'https://creativecommons.org/licenses/by-sa/3.0/dk/' },
  { label: 'CC BY-ND 3.0 DK', value: 'https://creativecommons.org/licenses/by-nd/3.0/dk/' },
  { label: 'CC BY-NC 3.0 DK', value: 'https://creativecommons.org/licenses/by-nc/3.0/dk/' },
  { label: 'CC BY-NC-SA 3.0 DK', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/dk/' },
  { label: 'CC BY-NC-ND 3.0 DK', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/dk/' },
  { label: 'CC BY 3.0 ES', value: 'https://creativecommons.org/licenses/by/3.0/es/' },
  { label: 'CC BY-SA 3.0 ES', value: 'https://creativecommons.org/licenses/by-sa/3.0/es/' },
  { label: 'CC BY-ND 3.0 ES', value: 'https://creativecommons.org/licenses/by-nd/3.0/es/' },
  { label: 'CC BY-NC 3.0 ES', value: 'https://creativecommons.org/licenses/by-nc/3.0/es/' },
  { label: 'CC BY-NC-SA 3.0 ES', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/es/' },
  { label: 'CC BY-NC-ND 3.0 ES', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/es/' },
  { label: 'CC BY 3.0 FI', value: 'https://creativecommons.org/licenses/by/3.0/fi/' },
  { label: 'CC BY-SA 3.0 FI', value: 'https://creativecommons.org/licenses/by-sa/3.0/fi/' },
  { label: 'CC BY-ND 3.0 FI', value: 'https://creativecommons.org/licenses/by-nd/3.0/fi/' },
  { label: 'CC BY-NC 3.0 FI', value: 'https://creativecommons.org/licenses/by-nc/3.0/fi/' },
  { label: 'CC BY-NC-SA 3.0 FI', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/fi/' },
  { label: 'CC BY-NC-ND 3.0 FI', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/fi/' },
  { label: 'CC BY 3.0 FR', value: 'https://creativecommons.org/licenses/by/3.0/fr/' },
  { label: 'CC BY-SA 3.0 FR', value: 'https://creativecommons.org/licenses/by-sa/3.0/fr/' },
  { label: 'CC BY-ND 3.0 FR', value: 'https://creativecommons.org/licenses/by-nd/3.0/fr/' },
  { label: 'CC BY-NC 3.0 FR', value: 'https://creativecommons.org/licenses/by-nc/3.0/fr/' },
  { label: 'CC BY-NC-SA 3.0 FR', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/fr/' },
  { label: 'CC BY-NC-ND 3.0 FR', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/fr/' },
  { label: 'CC BY 3.0 GB', value: 'https://creativecommons.org/licenses/by/3.0/gb/' },
  { label: 'CC BY-SA 3.0 GB', value: 'https://creativecommons.org/licenses/by-sa/3.0/gb/' },
  { label: 'CC BY-ND 3.0 GB', value: 'https://creativecommons.org/licenses/by-nd/3.0/gb/' },
  { label: 'CC BY-NC 3.0 GB', value: 'https://creativecommons.org/licenses/by-nc/3.0/gb/' },
  { label: 'CC BY-NC-SA 3.0 GB', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/gb/' },
  { label: 'CC BY-NC-ND 3.0 GB', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/gb/' },
  { label: 'CC BY 3.0 GR', value: 'https://creativecommons.org/licenses/by/3.0/gr/' },
  { label: 'CC BY-SA 3.0 GR', value: 'https://creativecommons.org/licenses/by-sa/3.0/gr/' },
  { label: 'CC BY-ND 3.0 GR', value: 'https://creativecommons.org/licenses/by-nd/3.0/gr/' },
  { label: 'CC BY-NC 3.0 GR', value: 'https://creativecommons.org/licenses/by-nc/3.0/gr/' },
  { label: 'CC BY-NC-SA 3.0 GR', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/gr/' },
  { label: 'CC BY-NC-ND 3.0 GR', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/gr/' },
  { label: 'CC BY 3.0 HU', value: 'https://creativecommons.org/licenses/by/3.0/hu/' },
  { label: 'CC BY-SA 3.0 HU', value: 'https://creativecommons.org/licenses/by-sa/3.0/hu/' },
  { label: 'CC BY-ND 3.0 HU', value: 'https://creativecommons.org/licenses/by-nd/3.0/hu/' },
  { label: 'CC BY-NC 3.0 HU', value: 'https://creativecommons.org/licenses/by-nc/3.0/hu/' },
  { label: 'CC BY-NC-SA 3.0 HU', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/hu/' },
  { label: 'CC BY-NC-ND 3.0 HU', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/hu/' },
  { label: 'CC BY 3.0 IE', value: 'https://creativecommons.org/licenses/by/3.0/ie/' },
  { label: 'CC BY-SA 3.0 IE', value: 'https://creativecommons.org/licenses/by-sa/3.0/ie/' },
  { label: 'CC BY-ND 3.0 IE', value: 'https://creativecommons.org/licenses/by-nd/3.0/ie/' },
  { label: 'CC BY-NC 3.0 IE', value: 'https://creativecommons.org/licenses/by-nc/3.0/ie/' },
  { label: 'CC BY-NC-SA 3.0 IE', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/ie/' },
  { label: 'CC BY-NC-ND 3.0 IE', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/ie/' },
  { label: 'CC BY 3.0 IL', value: 'https://creativecommons.org/licenses/by/3.0/il/' },
  { label: 'CC BY-SA 3.0 IL', value: 'https://creativecommons.org/licenses/by-sa/3.0/il/' },
  { label: 'CC BY-ND 3.0 IL', value: 'https://creativecommons.org/licenses/by-nd/3.0/il/' },
  { label: 'CC BY-NC 3.0 IL', value: 'https://creativecommons.org/licenses/by-nc/3.0/il/' },
  { label: 'CC BY-NC-SA 3.0 IL', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/il/' },
  { label: 'CC BY-NC-ND 3.0 IL', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/il/' },
  { label: 'CC BY 3.0 IS', value: 'https://creativecommons.org/licenses/by/3.0/is/' },
  { label: 'CC BY-SA 3.0 IS', value: 'https://creativecommons.org/licenses/by-sa/3.0/is/' },
  { label: 'CC BY-ND 3.0 IS', value: 'https://creativecommons.org/licenses/by-nd/3.0/is/' },
  { label: 'CC BY-NC 3.0 IS', value: 'https://creativecommons.org/licenses/by-nc/3.0/is/' },
  { label: 'CC BY-NC-SA 3.0 IS', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/is/' },
  { label: 'CC BY-NC-ND 3.0 IS', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/is/' },
  { label: 'CC BY 3.0 IT', value: 'https://creativecommons.org/licenses/by/3.0/it/' },
  { label: 'CC BY-SA 3.0 IT', value: 'https://creativecommons.org/licenses/by-sa/3.0/it/' },
  { label: 'CC BY-ND 3.0 IT', value: 'https://creativecommons.org/licenses/by-nd/3.0/it/' },
  { label: 'CC BY-NC 3.0 IT', value: 'https://creativecommons.org/licenses/by-nc/3.0/it/' },
  { label: 'CC BY-NC-SA 3.0 IT', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/it/' },
  { label: 'CC BY-NC-ND 3.0 IT', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/it/' },
  { label: 'CC BY 3.0 JP', value: 'https://creativecommons.org/licenses/by/3.0/jp/' },
  { label: 'CC BY-SA 3.0 JP', value: 'https://creativecommons.org/licenses/by-sa/3.0/jp/' },
  { label: 'CC BY-ND 3.0 JP', value: 'https://creativecommons.org/licenses/by-nd/3.0/jp/' },
  { label: 'CC BY-NC 3.0 JP', value: 'https://creativecommons.org/licenses/by-nc/3.0/jp/' },
  { label: 'CC BY-NC-SA 3.0 JP', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/jp/' },
  { label: 'CC BY-NC-ND 3.0 JP', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/jp/' },
  { label: 'CC BY 3.0 KR', value: 'https://creativecommons.org/licenses/by/3.0/kr/' },
  { label: 'CC BY-SA 3.0 KR', value: 'https://creativecommons.org/licenses/by-sa/3.0/kr/' },
  { label: 'CC BY-ND 3.0 KR', value: 'https://creativecommons.org/licenses/by-nd/3.0/kr/' },
  { label: 'CC BY-NC 3.0 KR', value: 'https://creativecommons.org/licenses/by-nc/3.0/kr/' },
  { label: 'CC BY-NC-SA 3.0 KR', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/kr/' },
  { label: 'CC BY-NC-ND 3.0 KR', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/kr/' },
  { label: 'CC BY 3.0 LU', value: 'https://creativecommons.org/licenses/by/3.0/lu/' },
  { label: 'CC BY-SA 3.0 LU', value: 'https://creativecommons.org/licenses/by-sa/3.0/lu/' },
  { label: 'CC BY-ND 3.0 LU', value: 'https://creativecommons.org/licenses/by-nd/3.0/lu/' },
  { label: 'CC BY-NC 3.0 LU', value: 'https://creativecommons.org/licenses/by-nc/3.0/lu/' },
  { label: 'CC BY-NC-SA 3.0 LU', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/lu/' },
  { label: 'CC BY-NC-ND 3.0 LU', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/lu/' },
  { label: 'CC BY 3.0 MX', value: 'https://creativecommons.org/licenses/by/3.0/mx/' },
  { label: 'CC BY-SA 3.0 MX', value: 'https://creativecommons.org/licenses/by-sa/3.0/mx/' },
  { label: 'CC BY-ND 3.0 MX', value: 'https://creativecommons.org/licenses/by-nd/3.0/mx/' },
  { label: 'CC BY-NC 3.0 MX', value: 'https://creativecommons.org/licenses/by-nc/3.0/mx/' },
  { label: 'CC BY-NC-SA 3.0 MX', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/mx/' },
  { label: 'CC BY-NC-ND 3.0 MX', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/mx/' },
  { label: 'CC BY 3.0 NL', value: 'https://creativecommons.org/licenses/by/3.0/nl/' },
  { label: 'CC BY-SA 3.0 NL', value: 'https://creativecommons.org/licenses/by-sa/3.0/nl/' },
  { label: 'CC BY-ND 3.0 NL', value: 'https://creativecommons.org/licenses/by-nd/3.0/nl/' },
  { label: 'CC BY-NC 3.0 NL', value: 'https://creativecommons.org/licenses/by-nc/3.0/nl/' },
  { label: 'CC BY-NC-SA 3.0 NL', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/nl/' },
  { label: 'CC BY-NC-ND 3.0 NL', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/nl/' },
  { label: 'CC BY 3.0 NZ', value: 'https://creativecommons.org/licenses/by/3.0/nz/' },
  { label: 'CC BY-SA 3.0 NZ', value: 'https://creativecommons.org/licenses/by-sa/3.0/nz/' },
  { label: 'CC BY-ND 3.0 NZ', value: 'https://creativecommons.org/licenses/by-nd/3.0/nz/' },
  { label: 'CC BY-NC 3.0 NZ', value: 'https://creativecommons.org/licenses/by-nc/3.0/nz/' },
  { label: 'CC BY-NC-SA 3.0 NZ', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/nz/' },
  { label: 'CC BY-NC-ND 3.0 NZ', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/nz/' },
  { label: 'CC BY 3.0 NO', value: 'https://creativecommons.org/licenses/by/3.0/no/' },
  { label: 'CC BY-SA 3.0 NO', value: 'https://creativecommons.org/licenses/by-sa/3.0/no/' },
  { label: 'CC BY-ND 3.0 NO', value: 'https://creativecommons.org/licenses/by-nd/3.0/no/' },
  { label: 'CC BY-NC 3.0 NO', value: 'https://creativecommons.org/licenses/by-nc/3.0/no/' },
  { label: 'CC BY-NC-SA 3.0 NO', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/no/' },
  { label: 'CC BY-NC-ND 3.0 NO', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/no/' },
  { label: 'CC BY 3.0 PE', value: 'https://creativecommons.org/licenses/by/3.0/pe/' },
  { label: 'CC BY-SA 3.0 PE', value: 'https://creativecommons.org/licenses/by-sa/3.0/pe/' },
  { label: 'CC BY-ND 3.0 PE', value: 'https://creativecommons.org/licenses/by-nd/3.0/pe/' },
  { label: 'CC BY-NC 3.0 PE', value: 'https://creativecommons.org/licenses/by-nc/3.0/pe/' },
  { label: 'CC BY-NC-SA 3.0 PE', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/pe/' },
  { label: 'CC BY-NC-ND 3.0 PE', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/pe/' },
  { label: 'CC BY 3.0 PL', value: 'https://creativecommons.org/licenses/by/3.0/pl/' },
  { label: 'CC BY-SA 3.0 PL', value: 'https://creativecommons.org/licenses/by-sa/3.0/pl/' },
  { label: 'CC BY-ND 3.0 PL', value: 'https://creativecommons.org/licenses/by-nd/3.0/pl/' },
  { label: 'CC BY-NC 3.0 PL', value: 'https://creativecommons.org/licenses/by-nc/3.0/pl/' },
  { label: 'CC BY-NC-SA 3.0 PL', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/pl/' },
  { label: 'CC BY-NC-ND 3.0 PL', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/pl/' },
  { label: 'CC BY 3.0 PT', value: 'https://creativecommons.org/licenses/by/3.0/pt/' },
  { label: 'CC BY-SA 3.0 PT', value: 'https://creativecommons.org/licenses/by-sa/3.0/pt/' },
  { label: 'CC BY-ND 3.0 PT', value: 'https://creativecommons.org/licenses/by-nd/3.0/pt/' },
  { label: 'CC BY-NC 3.0 PT', value: 'https://creativecommons.org/licenses/by-nc/3.0/pt/' },
  { label: 'CC BY-NC-SA 3.0 PT', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/pt/' },
  { label: 'CC BY-NC-ND 3.0 PT', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/pt/' },
  { label: 'CC BY 3.0 RU', value: 'https://creativecommons.org/licenses/by/3.0/ru/' },
  { label: 'CC BY-SA 3.0 RU', value: 'https://creativecommons.org/licenses/by-sa/3.0/ru/' },
  { label: 'CC BY-ND 3.0 RU', value: 'https://creativecommons.org/licenses/by-nd/3.0/ru/' },
  { label: 'CC BY-NC 3.0 RU', value: 'https://creativecommons.org/licenses/by-nc/3.0/ru/' },
  { label: 'CC BY-NC-SA 3.0 RU', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/ru/' },
  { label: 'CC BY-NC-ND 3.0 RU', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/ru/' },
  { label: 'CC BY 3.0 SE', value: 'https://creativecommons.org/licenses/by/3.0/se/' },
  { label: 'CC BY-SA 3.0 SE', value: 'https://creativecommons.org/licenses/by-sa/3.0/se/' },
  { label: 'CC BY-ND 3.0 SE', value: 'https://creativecommons.org/licenses/by-nd/3.0/se/' },
  { label: 'CC BY-NC 3.0 SE', value: 'https://creativecommons.org/licenses/by-nc/3.0/se/' },
  { label: 'CC BY-NC-SA 3.0 SE', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/se/' },
  { label: 'CC BY-NC-ND 3.0 SE', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/se/' },
  { label: 'CC BY 3.0 SG', value: 'https://creativecommons.org/licenses/by/3.0/sg/' },
  { label: 'CC BY-SA 3.0 SG', value: 'https://creativecommons.org/licenses/by-sa/3.0/sg/' },
  { label: 'CC BY-ND 3.0 SG', value: 'https://creativecommons.org/licenses/by-nd/3.0/sg/' },
  { label: 'CC BY-NC 3.0 SG', value: 'https://creativecommons.org/licenses/by-nc/3.0/sg/' },
  { label: 'CC BY-NC-SA 3.0 SG', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/sg/' },
  { label: 'CC BY-NC-ND 3.0 SG', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/sg/' },
  { label: 'CC BY 3.0 TR', value: 'https://creativecommons.org/licenses/by/3.0/tr/' },
  { label: 'CC BY-SA 3.0 TR', value: 'https://creativecommons.org/licenses/by-sa/3.0/tr/' },
  { label: 'CC BY-ND 3.0 TR', value: 'https://creativecommons.org/licenses/by-nd/3.0/tr/' },
  { label: 'CC BY-NC 3.0 TR', value: 'https://creativecommons.org/licenses/by-nc/3.0/tr/' },
  { label: 'CC BY-NC-SA 3.0 TR', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/tr/' },
  { label: 'CC BY-NC-ND 3.0 TR', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/tr/' },
  { label: 'CC BY 3.0 US', value: 'https://creativecommons.org/licenses/by/3.0/us/' },
  { label: 'CC BY-SA 3.0 US', value: 'https://creativecommons.org/licenses/by-sa/3.0/us/' },
  { label: 'CC BY-ND 3.0 US', value: 'https://creativecommons.org/licenses/by-nd/3.0/us/' },
  { label: 'CC BY-NC 3.0 US', value: 'https://creativecommons.org/licenses/by-nc/3.0/us/' },
  { label: 'CC BY-NC-SA 3.0 US', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/us/' },
  { label: 'CC BY-NC-ND 3.0 US', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/us/' },
  { label: 'CC BY 3.0 VE', value: 'https://creativecommons.org/licenses/by/3.0/ve/' },
  { label: 'CC BY-SA 3.0 VE', value: 'https://creativecommons.org/licenses/by-sa/3.0/ve/' },
  { label: 'CC BY-ND 3.0 VE', value: 'https://creativecommons.org/licenses/by-nd/3.0/ve/' },
  { label: 'CC BY-NC 3.0 VE', value: 'https://creativecommons.org/licenses/by-nc/3.0/ve/' },
  { label: 'CC BY-NC-SA 3.0 VE', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/ve/' },
  { label: 'CC BY-NC-ND 3.0 VE', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/ve/' },
  { label: 'CC BY 3.0 ZA', value: 'https://creativecommons.org/licenses/by/3.0/za/' },
  { label: 'CC BY-SA 3.0 ZA', value: 'https://creativecommons.org/licenses/by-sa/3.0/za/' },
  { label: 'CC BY-ND 3.0 ZA', value: 'https://creativecommons.org/licenses/by-nd/3.0/za/' },
  { label: 'CC BY-NC 3.0 ZA', value: 'https://creativecommons.org/licenses/by-nc/3.0/za/' },
  { label: 'CC BY-NC-SA 3.0 ZA', value: 'https://creativecommons.org/licenses/by-nc-sa/3.0/za/' },
  { label: 'CC BY-NC-ND 3.0 ZA', value: 'https://creativecommons.org/licenses/by-nc-nd/3.0/za/' },
];
