export const HELPER_TEXT = {
  WORK_ABSTRACT: 'Enter the abstract of the work.',
  WORK_SHORT_ABSTRACT: 'Enter the short abstract of the work.',
  WORK_TITLE: 'Enter the title of the work.',
  PLACE: 'Enter the place of the work.',
  SUBTITLE: 'Enter the subtitle of the work.',
  EDITION: 'Enter the edition of the work.',
  WITHDRAWN_DATE: 'Enter the withdrawn date of the work.',
  PUBLICATION_DATE: 'Enter the publication date of the work.',
  WORK_TYPE: 'Choose the type of work.',
  WORK_STATUS: 'Change the status of the work.',
  IMPRINT: 'Choose the imprint of the work.',
  LICENSE: 'Choose the license of the work.',
  COPYRIGHT_HOLDER: 'Choose the copyright holder of the work.',
  LANDING_PAGE: 'Enter the landing page URL of the work.',
  COVER_URL: 'Enter the URL to the work`s online cover image.',
  DOI: 'Enter the DOI URL of the work.',
  FULL_NAME: 'Enter the full name.',
  FIRST_NAME: 'Enter the given name(s) and/or initial(s).',
  LAST_NAME: 'Enter the family name(s).',
  CONTRIBUTOR_TYPE: 'Choose the type of contributor.',
  CONTRIBUTOR_BIOGRAPHY: 'Enter the biography of the contributor at the point of publication.',
  CONTRIBUTOR_ORCID: 'Enter the ORCID of the contributor.',
  CONTRIBUTOR_WEBSITE_URL: 'Enter the website URL of the contributor.',
  CONTRIBUTOR_AFFILIATION: 'Choose the affiliated institution of the contributor at the point of publication.',
  CONTRIBUTOR_AFFILIATION_POSITION:
    'Enter the position of the contributor at the affiliated institution at the point of publication.',
  WORK_TABLE_COUNT: 'Enter the table count of the work.',
  WORK_IMAGE_COUNT: 'Enter the image count of the work.',
  WORK_AUDIO_COUNT: 'Enter the audio count of the work.',
  WORK_VIDEO_COUNT: 'Enter the video count of the work.',
  WORK_PAGES_COUNT: 'Enter the page count of the work.',
  WORK_FRONTMATTER_COUNT: 'Enter the frontmatter page count of the work.',
  WORK_BACKMATTER_COUNT: 'Enter the backmatter page count of the work.',
  WORK_FIRST_PAGE: 'Enter the first page of the work.',
  WORK_LAST_PAGE: 'Enter the last page of the work.',
  WORK_GENERAL_NOTE: 'Enter the general note of the work.',
  WORK_BIBLIOGRAPHY_NOTE: 'Enter the bibliography note of the work.',
  PUBLICATION_TYPE: 'Choose the type of publication.',
  PUBLICATION_ISBN: 'Enter the ISBN of the publication.',
  PUBLICATION_WIDTH: 'Enter the width of the publication.',
  PUBLICATION_HEIGHT: 'Enter the height of the publication.',
  PUBLICATION_DEPTH: 'Enter the depth of the publication.',
  PUBLICATION_WEIGHT: 'Enter the weight of the publication.',
  PUBLICATION_ACCESSIBILITY_STANDARD: 'Select the accessibility standard of the publication.',
  PUBLICATION_ACCESSIBILITY_EXCEPTION: 'Select the accessibility exception of the publication.',
  PUBLICATION_ACCESSIBILITY_REPORT_URL: 'Enter the accessibility report URL or report of the publication.',
  PRICE_CURRENCY: 'Choose the currency of the price.',
  PRICE_VALUE: 'Enter the value of the price.',
  LOCATION_PLATFORM: 'Choose the platform of the publication.',
  LOCATION_URL_HELPER_TEXT: 'Enter the URL where a publication can be directly accessed or downloaded.',
  LANDING_PAGE_HELPER_TEXT: 'Enter the landing page URL of the publication.',
  INSTITUTION: 'Select the institution of the funding.',
  GRANT_NUMBER: 'Enter the grant number of the funding.',
  JURISDICTION: 'Enter the jurisdiction of the funding.',
  PROGRAM: 'Enter the program of the funding.',
  PROJECT_NAME: 'Enter the project name of the funding.',
  PROJECT_SHORTNAME: 'Enter the project shortname of the funding.',
  REFERENCE_URL: 'Enter the URL of the reference.',
  REFERENCE_CITATION: 'Enter the citation text of the reference.',
  REFERENCE_DOI: 'Enter the DOI of the reference.',
  PUBLISHER_CONTACT: 'Choose the contact of the publisher.',
  PUBLISHER_REPORT:
    'Enter the accessibility report or accessibility report URL of the publisher for readers with impairments.',
  PUBLISHER_STATEMENT: 'Enter the accessibility statement of the publisher for readers with impairments.',
  WORK_LCCN: 'Enter the LCCN of the work.',
  WORK_OCLC: 'Enter the OCLC number of the work.',
  WORK_SERIES: 'Choose the series the work belongs to.',
  WORK_SERIES_ORDINAL: 'Enter the volume number of the work in the series.',
  WORK_LANGUAGE: 'Choose the language of the work.',
  WORK_LANGUAGE_RELATION: 'Choose the language relation of the work.',
  WORK_INTERNAL_ID: 'Enter the internal ID of the work.',
};
