export const HELPER_TEXT = {
  WORK_TYPE: 'Choose the type of work.',
  IMPRINT: 'Choose the imprint of the work.',
  LICENSE: 'Choose the license of the work.',
  COPYRIGHT_HOLDER: 'Choose the copyright holder of the work.',
  LANDING_PAGE: 'Enter the landing page URL of the work.',
  COVER_URL: 'Enter the cover URL of the work.',
  DOI: 'Enter the DOI URL of the work.',
  FULL_NAME: 'Enter the full name.',
  FIRST_NAME: 'Enter the first name.',
  LAST_NAME: 'Enter the last name.',
  CONTRIBUTOR_TYPE: 'Choose the type of contributor.',
  CONTRIBUTOR_BIOGRAPHY: 'Enter the biography of the contributor.',
  CONTRIBUTOR_ORCID: 'Enter the ORCID ID of the contributor.',
  CONTRIBUTOR_WEBSITE_URL: 'Enter the website URL of the contributor.',
  WORK_TABLE_COUNT: 'Enter the table count of the work.',
  WORK_IMAGE_COUNT: 'Enter the image count of the work.',
  WORK_AUDIO_COUNT: 'Enter the audio count of the work.',
  WORK_VIDEO_COUNT: 'Enter the video count of the work.',
};
