export const HELPER_TEXT = {
  WITHDRAWN_DATE: 'Enter the withdrawn date of the work.',
  PUBLICATION_DATE: 'Enter the publication date of the work.',
  WORK_TYPE: 'Choose the type of work.',
  WORK_STATUS: 'Choose the status of the work.',
  IMPRINT: 'Choose the imprint of the work.',
  LICENSE: 'Choose the license of the work.',
  COPYRIGHT_HOLDER: 'Choose the copyright holder of the work.',
  LANDING_PAGE: 'Enter the landing page URL of the work.',
  COVER_URL: 'Enter the cover URL of the work.',
  DOI: 'Enter the DOI URL of the work.',
  FULL_NAME: 'Enter the full name.',
  FIRST_NAME: 'Enter the first name.',
  LAST_NAME: 'Enter the last name.',
  CONTRIBUTOR_TYPE: 'Choose the type of contributor.',
  CONTRIBUTOR_BIOGRAPHY: 'Enter the biography of the contributor.',
  CONTRIBUTOR_ORCID: 'Enter the ORCID ID of the contributor.',
  CONTRIBUTOR_WEBSITE_URL: 'Enter the website URL of the contributor.',
  WORK_TABLE_COUNT: 'Enter the table count of the work.',
  WORK_IMAGE_COUNT: 'Enter the image count of the work.',
  WORK_AUDIO_COUNT: 'Enter the audio count of the work.',
  WORK_VIDEO_COUNT: 'Enter the video count of the work.',
  WORK_PAGES_COUNT: 'Enter the pages count of the work.',
  WORK_FRONTMATTER_COUNT: 'Enter the frontmatter count of the work.',
  WORK_BACKMATTER_COUNT: 'Enter the backmatter count of the work.',
  PUBLICATION_TYPE: 'Choose the type of publication.',
  PUBLICATION_ISBN: 'Enter the ISBN of the publication.',
  PUBLICATION_WIDTH: 'Enter the width of the publication.',
  PUBLICATION_HEIGHT: 'Enter the height of the publication.',
  PUBLICATION_DEPTH: 'Enter the depth of the publication.',
  PUBLICATION_WEIGHT: 'Enter the weight of the publication.',
  PRICE_CURRENCY: 'Choose the currency of the price.',
  PRICE_VALUE: 'Enter the value of the price.',
  LOCATION_PLATFORM: 'Choose the platform of the publication.',
  LOCATION_URL_HELPER_TEXT: 'Enter the URL where a publication can be acquired or viewed.',
  LANDING_PAGE_HELPER_TEXT: 'Enter the landing page URL of the publication.',
  INSTITUTION: 'Select the institution of the funding.',
  GRANT_NUMBER: 'Enter the grant number of the funding.',
  JURISDICTION: 'Enter the jurisdiction of the funding.',
  PROGRAM: 'Enter the program of the funding.',
  PROJECT_NAME: 'Enter the project name of the funding.',
  PROJECT_SHORTNAME: 'Enter the project shortname of the funding.',
  REFERENCE_URL: 'Enter the URL of the reference.',
  REFERENCE_CITATION: 'Enter the citation of the reference.',
};
