export const NOTIFICATIONS = {
  // Auth
  AUTH_FAILED: 'authFailed',
  // Works
  WORK_CREATION_SUCCESS: 'workCreationSuccess',
  WORK_CREATION_FAILED: 'workCreationFailed',
  WORK_BULK_CREATION_SUCCESS: 'workBulkCreationSuccess',
  WORK_BULK_CREATION_FAILED: 'workBulkCreationFailed',
  WORK_UPDATE_FAILED: 'workUpdateFailed',
  WORK_DELETE_SUCCESS: 'workDeleteSuccess',
  WORK_DELETE_FAILED: 'workDeleteFailed',
  WORK_EDITION_CREATION_SUCCESS: 'workEditionCreationSuccess',
  WORK_EDITION_CREATION_FAILED: 'workEditionCreationFailed',
  WORK_TRANSLATION_CREATION_SUCCESS: 'workTranslationCreationSuccess',
  WORK_TRANSLATION_CREATION_FAILED: 'workTranslationCreationFailed',
  WORK_CONTRIBUTION_CREATION_FAILED: 'workContributionCreationFailed',
  WORK_CONTRIBUTION_DELETION_FAILED: 'workContributionDeletionFailed',
  WORK_CONTRIBUTION_UPDATE_FAILED: 'workContributionUpdateFailed',
  WORK_MOVE_RELATION_FAILED: 'workMoveRelationFailed',
  // Chapters
  CHAPTER_CREATION_SUCCESS: 'chapterCreationSuccess',
  CHAPTER_CREATION_FAILED: 'chapterCreationFailed',
  CHAPTER_UPDATE_FAILED: 'chapterUpdateFailed',
  CHAPTER_DELETE_FAILED: 'chapterDeleteFailed',
  // Contributors
  CONTRIBUTOR_CREATION_SUCCESS: 'contributorCreationSuccess',
  CONTRIBUTOR_CREATION_FAILED: 'contributorCreationFailed',
  CONTRIBUTOR_UPDATE_SUCCESS: 'contributorUpdateSuccess',
  CONTRIBUTOR_UPDATE_FAILED: 'contributorUpdateFailed',
  CONTRIBUTION_MOVE_FAILED: 'contributionMoveFailed',
  // Affiliations
  AFFILIATION_CREATION_SUCCESS: 'affiliationCreationSuccess',
  AFFILIATION_CREATION_FAILED: 'affiliationCreationFailed',
  AFFILIATION_UPDATE_SUCCESS: 'affiliationUpdateSuccess',
  AFFILIATION_UPDATE_FAILED: 'affiliationUpdateFailed',
  AFFILIATION_MOVE_FAILED: 'affiliationMoveFailed',
  // Languages
  LANGUAGE_CREATION_FAILED: 'languageCreationFailed',
  LANGUAGE_UPDATE_FAILED: 'languageUpdateFailed',
  LANGUAGE_DELETE_FAILED: 'languageDeleteFailed',
  // Publications
  PUBLICATION_CREATION_FAILED: 'publicationCreationFailed',
  PUBLICATION_UPDATE_FAILED: 'publicationUpdateFailed',
  // Prices
  PRICE_CREATION_FAILED: 'priceCreationFailed',
  PRICE_UPDATE_FAILED: 'priceUpdateFailed',
  PRICE_DELETE_FAILED: 'priceDeleteFailed',
  // Locations
  LOCATION_DELETE_FAILED: 'locationDeleteFailed',
  LOCATION_UPDATE_FAILED: 'locationUpdateFailed',
  LOCATION_CREATE_FAILED: 'locationCreateFailed',
  // Fundings
  FUNDING_CREATION_FAILED: 'fundingCreationFailed',
  FUNDING_UPDATE_FAILED: 'fundingUpdateFailed',
  FUNDING_DELETE_FAILED: 'fundingDeleteFailed',
  // References
  REFERENCE_CREATION_FAILED: 'referenceCreationFailed',
  REFERENCE_UPDATE_FAILED: 'referenceUpdateFailed',
  REFERENCE_DELETE_FAILED: 'referenceDeleteFailed',
  REFERENCE_MOVE_FAILED: 'referenceMoveFailed',
  // Awards
  AWARD_CREATION_FAILED: 'awardCreationFailed',
  AWARD_UPDATE_FAILED: 'awardUpdateFailed',
  AWARD_DELETE_FAILED: 'awardDeleteFailed',
  AWARD_MOVE_FAILED: 'awardMoveFailed',
  // Endorsements
  ENDORSEMENT_CREATION_FAILED: 'endorsementCreationFailed',
  ENDORSEMENT_UPDATE_FAILED: 'endorsementUpdateFailed',
  ENDORSEMENT_DELETE_FAILED: 'endorsementDeleteFailed',
  ENDORSEMENT_MOVE_FAILED: 'endorsementMoveFailed',
  // Book Reviews
  BOOK_REVIEW_CREATION_FAILED: 'bookReviewCreationFailed',
  BOOK_REVIEW_UPDATE_FAILED: 'bookReviewUpdateFailed',
  BOOK_REVIEW_DELETE_FAILED: 'bookReviewDeleteFailed',
  BOOK_REVIEW_MOVE_FAILED: 'bookReviewMoveFailed',
  // Additional Resources
  ADDITIONAL_RESOURCE_CREATION_FAILED: 'additionalResourceCreationFailed',
  ADDITIONAL_RESOURCE_UPDATE_FAILED: 'additionalResourceUpdateFailed',
  ADDITIONAL_RESOURCE_DELETE_FAILED: 'additionalResourceDeleteFailed',
  ADDITIONAL_RESOURCE_MOVE_FAILED: 'additionalResourceMoveFailed',
  // Subjects
  SUBJECT_CREATION_FAILED: 'subjectCreationFailed',
  SUBJECT_UPDATE_FAILED: 'subjectUpdateFailed',
  SUBJECT_DELETE_FAILED: 'subjectDeleteFailed',
  SUBJECT_MOVE_FAILED: 'subjectMoveFailed',
  // Series
  SERIES_CREATION_FAILED: 'seriesCreationFailed',
  SERIES_UPDATE_FAILED: 'seriesUpdateFailed',
  SERIES_DELETE_FAILED: 'seriesDeleteFailed',
  // Issues
  ISSUE_CREATION_FAILED: 'issueCreationFailed',
  ISSUE_UPDATE_FAILED: 'issueUpdateFailed',
  ISSUE_DELETE_FAILED: 'issueDeleteFailed',
  ISSUE_MOVE_FAILED: 'issueMoveFailed',
  // Titles
  TITLE_CREATION_FAILED: 'titleCreationFailed',
  TITLE_UPDATE_FAILED: 'titleUpdateFailed',
  TITLE_DELETE_FAILED: 'titleDeleteFailed',
  // Abstracts
  ABSTRACT_CREATION_FAILED: 'abstractCreationFailed',
  ABSTRACT_UPDATE_FAILED: 'abstractUpdateFailed',
  ABSTRACT_DELETE_FAILED: 'abstractDeleteFailed',
  // Publishers
  PUBLISHER_CONTACT_CREATION_FAILED: 'publisherContactCreationFailed',
  PUBLISHER_CONTACT_DELETION_FAILED: 'publisherContactDeletionFailed',
  PUBLISHER_CONTACT_UPDATE_FAILED: 'publisherContactUpdateFailed',
  PUBLISHER_UPDATE_FAILED: 'publisherUpdateFailed',
  PUBLISHER_CREATION_FAILED: 'publisherCreationFailed',
  // Biographies
  BIOGRAPHY_CREATION_FAILED: 'biographyCreationFailed',
  BIOGRAPHY_UPDATE_FAILED: 'biographyUpdateFailed',
  BIOGRAPHY_DELETE_FAILED: 'biographyDeleteFailed',
  // Sets
  SET_CREATION_FAILED: 'setCreationFailed',
  SET_UPDATE_FAILED: 'setUpdateFailed',
  SET_DELETE_FAILED: 'setDeleteFailed',
  SET_ADD_TO_FAILED: 'setAddToFailed',
  SET_DELETE_FROM_FAILED: 'setDeleteFromFailed',
  SET_MOVE_RELATION_FAILED: 'setMoveRelationFailed',
  // Imprints
  IMPRINT_CREATION_FAILED: 'imprintCreationFailed',
  // Featured Video
  FEATURED_VIDEO_CREATION_FAILED: 'featuredVideoCreationFailed',
  FEATURED_VIDEO_UPDATE_FAILED: 'featuredVideoUpdateFailed',
  FEATURED_VIDEO_DELETE_FAILED: 'featuredVideoDeleteFailed',
  // File Upload
  UPLOAD_FILE_FAILED: 'uploadFileFailed',
  PUBLICATION_UPLOAD_FILE_DISABLED: 'publicationUploadFileDisabled',
  DOI_IS_REQUIRED: 'doiIsRequired',
} as const;
