export const QueryKeys = {
  // BOOKS
  books: 'books',
  booksCount: 'booksCount',
  forthcomingBooksCount: 'forthcomingBooksCount',
  publishedBooksCount: 'publishedBooksCount',
  // WORKS
  work: 'work',
  works: 'works',
  worksCount: 'worksCount',
  workChapters: 'workChapters',
  workEditions: 'workEditions',
  workPrevEditions: 'workPrevEditions',
  translatedWorks: 'translatedWorks',
  workTranslations: 'workTranslations',
  workSet: 'workSet',
  // PUBLISHERS
  publisher: 'publisher',
  publishers: 'publishers',
  linkedPublishers: 'linkedPublishers',
  publishersCount: 'publishersCount',
  // FUNDINGS
  fundings: 'fundings',
  // INSTITUTIONS
  institutions: 'institutions',
  // CONTRIBUTORS
  contributor: 'contributor',
  contributors: 'contributors',
  // CONTRIBUTIONS
  contribution: 'contribution',
  // SERIESES
  series: 'series',
  serieses: 'serieses',
  seriesesCount: 'seriesesCount',
  // SETS
  sets: 'sets',
  setsCount: 'setsCount',
  set: 'set',
  bookSetWorks: 'bookSetWorks',
  // METADATA
  metadata: 'metadata',
  // USER
  userInfo: 'userInfo',
} as const;
