export const QueryKeys = {
  // BOOKS
  books: 'books',
  booksCount: 'booksCount',
  forthcomingBooksCount: 'forthcomingBooksCount',
  publishedBooksCount: 'publishedBooksCount',
  // WORKS
  work: 'work',
  works: 'works',
  worksCount: 'worksCount',
  workChapters: 'workChapters',
  workEditions: 'workEditions',
  workPrevEditions: 'workPrevEditions',
  translatedWorks: 'translatedWorks',
  workTranslations: 'workTranslations',
  // PUBLISHERS
  publisher: 'publisher',
  publishers: 'publishers',
  linkedPublishers: 'linkedPublishers',
  publishersCount: 'publishersCount',
  // FUNDINGS
  fundings: 'fundings',
  // INSTITUTIONS
  institutions: 'institutions',
  // CONTRIBUTORS
  contributor: 'contributor',
  contributors: 'contributors',
  // SERIESES
  series: 'series',
  serieses: 'serieses',
  seriesesCount: 'seriesesCount',
} as const;
